### ISSUE TITLE
Sonatype/Maven repos don't resolve

### ISSUE THREAD

**Issue by leftofnull** [ensime/ensime-sbt#100]
Getting 404 on the [jar](https://repo1.maven.org/maven2/org/ensime/ensime-sbt/0.1.7/ensime-sbt-0.1.7.jar) and 404 on the [pom](https://repo1.maven.org/maven2/org/ensime/ensime-sbt/0.1.7/ensime-sbt-0.1.7.pom). It does appear [on the search](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.ensime%22%20AND%20a%3A%22ensime-sbt%22) properly though.

**Comment by fommil** [comment]
Try nuking your caches and try again. Create a test repo if it continues.

**Comment by fommil** [comment]
This might be a maven central transient error.
