### ISSUE TITLE
Plugin should *not* change cancelable value

### ISSUE THREAD

**Issue by djspiewak** [ensime/ensime-sbt#103]
There's a reason that `cancelable` is `false` by default.  There are a huge number of situations where it just doesn't behave properly, even within the ensime-sbt plugin itself!  For example, I just tried to <kbd>ctrl</kbd>-<kbd>c</kbd> out of a hanging `gen-ensime` and it didn't work (I'm relatively certain because of ivy issues).  More generally, there are a large number of non-ensime scenarios where `cancelable := true` simply causes <kbd>ctrl</kbd>-<kbd>c</kbd> to no longer function.  For example, imagine running `test` where your test code uses concurrency to any extent.  An `InterruptedException` is almost certain to *not* behave the way you would want.

One thing that you could do if you *really* want <kbd>ctrl</kbd>-<kbd>c</kbd> to work for ensime-sbt is derive a new scope specifically for ensime tasks, and set `cancelable in Ensime := true` (or similar).

The long and short of it is that overriding global options that default to one thing is almost never a good idea.  `cancelable` defaults to `false` for a reason, and if users want <kbd>ctrl</kbd>-<kbd>c</kbd> to interrupt tasks, they should override it themselves.

**Comment by fommil** [comment]
Interesting. I guess I was thinking along the lines of when fork is true, it which case it would exit for tests. Is there any case where setting this to true actually changes the semantics such that it breaks what the user expects? The point is that c-c should break a running main or test, not that it should work globally.

**Comment by fommil** [comment]
C-c is extremely important when running with debugging enabled, so perhaps we could weaken what we're doing to force cancellable:=true when debugging is enabled, and return to the user's setting when debugging in disabled. How about that?

**Comment by djspiewak** [comment]
@fommil Even with `fork` is true, in my experience, it just raises an interrupt in whatever the active thread is in the tests.

I don't think you can change the value of setting keys dynamically in the manner you describe.  I honestly think you're better off creating an `Ensime` scope and setting `cancelable` to `true` in that scope.

**Comment by fommil** [comment]
You sure about fork? In my experience it sends KILL signals. It's a *terrible* under experience if C-c doesn't work when running in debugging and wanting to end the session. If we could capture C-c in that one scenario and Do The Right Thing, I'd be happy to revert the cancellable.

**Comment by fommil** [comment]
But it any case, did you get any further than this with your project? Did you give sublime a try? :-) if you encountered any problems, send a ticket with a link to the project and we'll take a look.

**Comment by fommil** [comment]
if this is blocking you from using ensime-sbt, we could consider reverting the `cancelable` setting and then putting a note in the install instructions. Also assigning all future tickets regarding this to you :stuck_out_tongue:

**Comment by fommil** [comment]
@djspiewak is this still putting you off ensime? I was thinking I might do as you suggest and then recommend people set it manually. Any idea what the magic command word be the do this globally? Is it an 'in ThisBuild' thing?
