### ISSUE TITLE
conflicts with scalariformat

### ISSUE THREAD

**Issue by caente** [ensime/ensime-sbt#104]
Hi, in our codebase we keep the formatting of the source code with scalariformat, but when the sbt-plugin is present, and we call scalariformat from sbt, it formats the source code according to some "hidden" parameters, are you aware of that? How can I shut it off?

**Comment by rorygraves** [comment]
Hi @caente I suspect this comment is relevent:
https://github.com/ensime/ensime-sbt/blob/master/build.sbt#L21

It sounds like there might be a scalariform version issue - I know for a fact there are multiple versions with breaking changes wrt to default formatting.

**Comment by fommil** [comment]
I have a ticket with scalariform to address this. Upstream bug.

**Comment by fommil** [comment]
Specifically this, please vote for the accompanying PR and get an many people an you can to jump in as well https://github.com/daniel-trinh/scalariform/issues/29 Also note my post on the scala-ide list, and additionally request @mdr to hand the repo over to an admin of scala-ide or ENSIME.

**Comment by fommil** [comment]
This is the PR: https://github.com/daniel-trinh/scalariform/pull/80

Tweet it, pile in on the scala-ide discussion, spam @mdr... Scalariform ownership to importance ratio is a mess.
