### ISSUE TITLE
 ')' expected but double literal found.  What should I do??

### ISSUE THREAD

**Issue by smartinsightsfromdata** [ensime/ensime-sbt#105]
I've installed ensime today (For SublimeText 3)  but I get this error when I start `sbt gen-ensime` in a project root and I'm not sure what to do.

I've installed `ensime-sbt` as per instructions:
````
plugins e$ echo "addSbtPlugin("org.ensime" % "ensime-sbt" % "0.2.0")" >> plugins.sb
````
Then at the project root I run `sbt gen-ensime` but I get an error.
````
hello-ensime e$ sbt gen-ensime
[error] [/Users/e/.sbt/0.13/plugins/plugins.sbt]:1: ')' expected but double literal found.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
````

**Comment by rorygraves** [comment]
I suspect if you open your plugins.sbt it does not contain the text
```addSbtPlugin("org.ensime" % "ensime-sbt" % "0.2.0")```
but some variation due to the quoting of your echo command. 

If this is not the issue can you please paste your plugins.sbt file?

**Comment by smartinsightsfromdata** [comment]
smashing!  I didn't have any quotes.  Many thanks!!

**Comment by lalet** [comment]
Thanks. The big data university course has the the same bug but when I tried with brackets it works. 

> addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "3.0.0")

Use this line and it should work fine.
