### ISSUE TITLE
debugging command can be applied twice

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-sbt#106]
If you mistakenly invoke the `debugging` command after you've already done it, duplicate debugging options are added to the JVM options, which means the forked JVM won't start, so you have to invoke `debugging-off` - not once, but twice.

**Comment by fommil** [comment]
Yes it's been designed to be stateful because SBT is awesome and this is the only way to do it. However, we shouldn't be adding flags twice. I thought we actually checked for that case. Do you have an example of a project on github that exhibits this?

**Comment by fommil** [comment]
This is where the magic happens, a PR in this area would be welcome https://github.com/ensime/ensime-sbt/blob/master/src/main/scala/EnsimePlugin.scala#L97

**Comment by fommil** [comment]
ok, I see how this can happen. I'll have a fix soon.
