### ISSUE TITLE
add extra field to the config for scala compiler jars

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#119]
scala-library, scala-compiler, scalap.

**Comment by fommil** [comment]
@lxol any preferences on the name of the key for the system jars? Maybe `:scala-jars` ?

**Comment by lxol** [comment]
@fommil  `:system-deps` ?

**Comment by fommil** [comment]
I prefer `:scala-compiler-jars` because it's self-describing. I don't know why I called these things system jars in the title.

**Comment by lxol** [comment]
ok

**Comment by fommil** [comment]
I'll try to do this over the next day or so

**Comment by fommil** [comment]
WIP here https://github.com/fommil/ensime-sbt/blob/scala-compiler-jars/src/main/scala/EnsimePlugin.scala (not working yet)

**Comment by fommil** [comment]
@lxol ok, the `:scala-compiler-jars` is now generated by the latest snapshot of `ensime-sbt`. I want to add one more feature then I'll make a maven central release.
