### ISSUE TITLE
Add a config option to specify a single .ensime_cache location common for all projects

### ISSUE THREAD

**Issue by alex3kov** [ensime/ensime-sbt#126]
Those .ensime_cache dirs are pretty large and they are per-project.
Would it be possible to specify a single (per user) location in ~/.sbt/0.13/plugins/plugins.sbt via gen-ensime options? Reasons:  
* Some projects use the same libraries, so it would de-duplicate things a bit;  
* User might place this .ensime_cache directory on a faster disk;  
* .ensime_cache directories in every project would get out of the way of automatic backup software, if one is used. Over 150 Mb per project is quite the space drag.

**Comment by fommil** [comment]
Ha! Yeah, not going to happen. I can explain why if you're oat Scala exchange. PRW.

**Comment by alex3kov** [comment]
Oh well. At least creating symbolic links to a different drive seems to work :)

**Comment by fommil** [comment]
Good luck with that :-D it'll break in unexpected ways. Taking a note of your name :-P
