### ISSUE TITLE
Cannot add dependency 'org.scala-lang#scala-compiler;2.10.5' to configuration 'ensime-internal'"

### ISSUE THREAD

**Issue by prassee** [ensime/ensime-sbt#140]
**TL;DR** your build definition is broken, see proposed solution below.

-----

I'm getting this error while using ensime-sbt in plugin.sbt

```
" Cannot add dependency 'org.scala-lang#scala-compiler;2.10.5' to configuration 'ensime-internal'"
```

I'm using 0.13.9 version of sbt

Here is my plugin.sbt

```scala
addSbtPlugin("org.ensime" % "ensime-sbt" % "0.3.1")
```

Here is the brief build.sbt

```scala
val project = Project(
id = "acds",
base = file("."),
settings = Project.defaultSettings ++ Seq(
name := "acds",
version := "2.4.0",
scalaVersion := "2.11.7",
scalacOptions in Compile ++= Seq("-encoding", "UTF-8", "-target:jvm-1.8", "-deprecation", "-feature", "-unchecked", "-Xlog-reflective-calls", "-Xlint"),
javacOptions in Compile ++= Seq("-source", "1.8", "-target", "1.8", "-Xlint:unchecked", "-Xlint:deprecation"),
libraryDependencies ++= Seq(
"com.typesafe.akka" %% "akka-actor" % akkaVersion),
javaOptions in run ++= Seq(
"-Xms128m", "-Xmx1024m", "-Djava.library.path=./target/native"),
Keys.fork in run := true
)
)
```

But it works fine when the build.sbt is changed to 

```scala
val akkaVersion = "2.4.0"
name := "acds"
version := "2.4.0"
scalaVersion := "2.11.7"
libraryDependencies ++= Seq(
      "com.typesafe.akka" %% "akka-actor" % akkaVersion)
```

I suspect if this is a enisime-sbt or build definition. Please help

**Comment by strobe** [comment]
Is it possible to create guide at documentation (with references to sbt related docs and issues) how to fix and understand that kind of issues at build configuration?
I asking because it seems like lot of big open source projects has it inside, for instance https://github.com/akka/akka has at least few these messages.

**Comment by fommil** [comment]
This ticket is the documentation from our side. Probably sbt mailgroups are the best place to ask. I'm not at all surprised that the akka build would be broken, I've never even been able to get it to build.

**Comment by strobe** [comment]
@fommil Thanks.
Sorry for few annoying questions below.

Could you describe best name which is suitable for refer this issue in sbt and akka communities?

What exactly part of ensime-sbt produced this sort of sbt build configuration conflicts? 

If I will try fix Akka build configuration and send PR - how can I describe to Akka devs why they need to accept this change besides "ability to use ensime for akka development"? - For me is seems like akka build configuration works well for Akka team and probably they will fix that only in case if at least will be some kind of proof that for sbt is exist "idiomatic" way to define settings that will works at any case. 

(Looks like Im not a first person why doesn't understand well relation between sbt concepts and errors like this:
https://stackoverflow.com/questions/35067187/sbt-idiomatic-way-to-add-settings )

**Comment by fommil** [comment]
Yeah. It's a major problem in the Scala community. Everybody just copies and pastes.

I recommend reading the failures above, there were some common patterns. I'd help if you could minimise the problem, but I'm not particularly keen on losing a day to trawling through akka config. I'd rather spend a day removing akka from ENSIME to be honest, because it's such a constant source of agony.

**Comment by strobe** [comment]
Thanks.
I will try investigate this more deeply by myself.

**Comment by fommil** [comment]
the typical problem is that the `rootProject` has not been set up correctly.

https://github.com/akka/akka/blob/master/project/AkkaBuild.scala#L39

at a guess, they need to do something like

```scala
override def rootProject = Some(root)
```

**Comment by fommil** [comment]
oh wow, it's worse than that. They are explicitly bypassing the default settings by providing one to the `root` project on construction. It basically works by accident.

**Comment by fommil** [comment]
try doing the above, plus change to

```scala
lazy val root = Project(
    id = "akka",
    base = file(".")
  ).settings( ...
```

**Comment by fommil** [comment]
actually, don't. They've done that everywhere, it'd be a major refactor, try just setting the `rootProject`

**Comment by strobe** [comment]
Just ```rootProject``` itself won't help, it has other issues at some of subproject like ```akka-samples```.
But anyway please do not spend time on that, thanks for help. 

I just would to understand source of that problem (not build the akka project) and I will try to do it by myself - May be later I will bring  some info back.

**Comment by strobe** [comment]
this works https://github.com/strobe/akka/commit/67dbdf400e2e543baa8ff141849c09edf980fdc8
(but not sure that is a right way)

**Comment by strobe** [comment]
I added few notes about 'settings =' & '.settings()' approaches difference:
http://stackoverflow.com/questions/35067187/sbt-idiomatic-way-to-add-settings
