### ISSUE TITLE
build.sbt projects getting erroneous error and missing scalacOptions

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#141]
The following simple project `build.sbt` triggers the "You have a different version of scala for your build and root project." error and the `scalacOptions` are not picked up for the `:compiler-args`

```scala
scalaVersion := "2.11.7"
scalacOptions in Compile := Seq("-Xlog-reflective-calls")
```

The corresponding `project/MyBuild.scala` **does** work in 0.3.0 but does not work in 0.3.1 so there is a regression (probably me adding all those `in ThisBuild` qualifiers in `EnsimePlugin.scala`)

```scala
import sbt._
import Keys._

object MyBuild extends Build {
  override val settings = super.settings ++ Seq(
    scalaVersion := "2.11.7",
    scalacOptions in Compile := Seq("-Xlog-reflective-calls")
  )
}
```

Probably something to do with the order in which our `AutoPlugin` is loaded. We should trigger after the `build.sbt` default settings are loaded.

@prassee is looking into setting up an `sbt-test` for this (probably two would be good, one for the `MyBuild.scala` approach and another for `build.sbt`, both defining the same project)

@gaydenko is this also similar to what you were seeing?

**Comment by gaydenko** [comment]
@fommil , yes, exactly!

**Comment by prassee** [comment]
Unfortunately , I still see this happening while I was on chat with @fommil  I told him that its working for a plain build.sbt.  However its really not because I later noticed that I'm still using 0.2.0 (Its a mistake on my side). Hence as @fommil mentioned the sbt-test may not work either :(

**Comment by fommil** [comment]
@gaydenko for future reference, the reproduction is only 2 lines long and I can do nothing until I have it.

**Comment by fommil** [comment]
@prassee that's the point of the tests, I was expecting falling tests

**Comment by fommil** [comment]
I've created a failing testcase in https://github.com/fommil/ensime-sbt/tree/fix-0.3.1-regressions

**Comment by fommil** [comment]
@gaydenko also for future reference, if you can show failures in the form of a simple project like https://github.com/ensime/ensime-sbt/tree/master/src/sbt-test/ensime-sbt then that will make it a lot easier to understand what you're seeing. Ideally, send in PRs with broken test projects. We have tests around `ensime-sbt` but they obviously aren't fully representing your projects so you can help out by increasing the test coverage and expectations.

**Comment by DylanLukes** [comment]
Is there a fix for this? It still seems to be happening.
