### ISSUE TITLE
Getting ERROR "You have a different version of scala for your build (2.10.5) and ... (2.10.6)"

### ISSUE THREAD

**Issue by pishen** [ensime/ensime-sbt#146]
git clone this project https://github.com/KKBOX/spark-deployer
And call `gen-ensime` with ensime-sbt 0.3.2 will give me the following error:
```
[info] ENSIME processing spark-deployer (spark-deployer)
[info] ENSIME processing cmd (spark-deployer-cmd)
[error] You have a different version of scala for your build (2.10.5) and cmd (2.10.6).
[error] It is highly likely that this is a mistake with your configuration.
[error] Please read https://github.com/ensime/ensime-sbt/issues/138
[info] ENSIME processing sbt (spark-deployer-sbt)
[error] You have a different version of scala for your build (2.10.5) and sbt (2.10.6).
[error] It is highly likely that this is a mistake with your configuration.
[error] Please read https://github.com/ensime/ensime-sbt/issues/138
[info] ENSIME processing core (spark-deployer-core)
[error] You have a different version of scala for your build (2.10.5) and core (2.10.6).
[error] It is highly likely that this is a mistake with your configuration.
[error] Please read https://github.com/ensime/ensime-sbt/issues/138
```
These errors didn't happen when using ensime-sbt 0.2.3.

**Comment by pishen** [comment]
Sorry I suddenly hit Enter...

**Comment by pishen** [comment]
Has updated the description.

**Comment by fommil** [comment]
And what do you think about the link in the stack trace that tells you exactly what is wrong?

**Comment by ancane** [comment]
@pishen Hi. I was curious to look into `spark-deployer` build definition and I found an interesting name clash. One of the modules is called `sbt` which makes defining project keys, like `scalaVersion`, impossible. That is because `sbt` is a namespace for sbt keys and settings which are implicitly imported into build.sbt via 'import sbt._, Keys._, dsl._'.
Check out and try `gen-ensime` here: https://github.com/ancane/spark-deployer.

**Comment by pishen** [comment]
Got it, thanks!
So the same warning now become error, right?
Will fix my project to fit the requirement, sorry for disturbing.

**Comment by fommil** [comment]
Glad to hear you fixed it :smile:
