### ISSUE TITLE
scripted tests fails on Mac OS

### ISSUE THREAD

**Issue by VlachJosef** [ensime/ensime-sbt#151]
When I run `scripted` tests on Mac OS all of them fails due to the fact that `/var` folder on Mac OS is symlink to `/private/var`. When `ensimeExpect` is doing replacing on lots of places it fails due to the path without resolved symlink. 

For example  `-Dsbt.global.base` from `java-flags` won't be deleted and thus test fails:
```
[info] [info] parsing /private/var/folders/w6/bgcydn5918s8jqsx8k09k2f80000gn/T/sbt_638919d6/simple-build.scala/.ensime
[info] [info] parsing /private/var/folders/w6/bgcydn5918s8jqsx8k09k2f80000gn/T/sbt_638919d6/simple-build.scala/gen-ensime.expect
[info] [error] .ensime diff: [ChangeDelta, position: 6, lines: 
[ :java-flags ("-XX:MaxPermSize=256m" "-Xmx2g" "-Xss2m")] to
[ :java-flags ("-XX:MaxPermSize=256m" "-Xmx2g" "-Xss2m" "-Dsbt.global.base=/var/folders/w6/bgcydn5918s8jqsx8k09k2f80000gn/T/sbt_638919d6/simple-build.scala/global")]]
```

In [EnsimeSbtTestSupport](https://github.com/ensime/ensime-sbt/blob/a5eeaa650e409fbc46bb297f7c2803ad01d3c9de/src/sbt-test/ensime-sbt/ensime-server/project/EnsimeSbtTestSupport.scala#L51) `baseDir.getCanonicalPath` resolves to path like `/private/var/folders/...`

So quickest workaround is to add line

```
replace(baseDir.getCanonicalPath.replace("/private", ""), "BASE_DIR").
```

just under line
```
replace(baseDir.getCanonicalPath, "BASE_DIR").
```

If such a workaround is preferable over symlink resolving/manipulation than I can provide pull request.

**Comment by fommil** [comment]
Is this a dupe?

**Comment by fommil** [comment]
Your workaround sounds good!
