### ISSUE TITLE
Debugging command does not do anything in sbt 0.13.5

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-sbt#155]
I have `set fork in run := true` (after running `debugging`).

**Comment by fommil** [comment]
This sounds like an SBT problem rather than ensime-sbt, can you show your Java options?

**Comment by fommil** [comment]
Did debugging put anything on the screen? Also try doing it after setting fork.

**Comment by fommil** [comment]
Oh, setting run here might only do it for the root project, you might need to do it for the subproject for multi-project  builds

**Comment by fommil** [comment]
Oh 0.13.5, can you update? That's ancient.
