### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot add dependency 'org.scala-lang#scala-compiler;2.10.5' to configuration 'ensime-internal'

### ISSUE THREAD

**Issue by vikraman** [ensime/ensime-sbt#156]
I have a fairly large multi project build, and I'm running into the same issue as #140 and #145, but cannot figure out how to fix it. I have put together a small repo to demonstrate the issue.

https://github.com/vikraman/ensime-sbt-bug

```
[master] foo: update
[info] Updating {file:/tmp/ensime-sbt-bug/}macros...
[info] Updating {file:/tmp/ensime-sbt-bug/}foo...
[trace] Stack trace suppressed: run last foo/*:update for the full output.
[trace] Stack trace suppressed: run last core/*:projectDescriptors for the full output.
[trace] Stack trace suppressed: run last macros/*:update for the full output.
[error] (foo/*:update) java.lang.IllegalArgumentException: Cannot add dependency 'org.scala-lang#scala-compiler;2.10.5' to configuration 'ensime-internal' of module foo#foo_2.10;0.1-SNAPSHOT because this configuration doesn't exist!
[error] (core/*:projectDescriptors) java.lang.IllegalArgumentException: Cannot add dependency 'org.scala-lang#scala-compiler;2.10.5' to configuration 'ensime-internal' of module macros#macros_2.10;0.1-SNAPSHOT because this configuration doesn't exist!
[error] (macros/*:update) java.lang.IllegalArgumentException: Cannot add dependency 'org.scala-lang#scala-compiler;2.10.5' to configuration 'ensime-internal' of module macros#macros_2.10;0.1-SNAPSHOT because this configuration doesn't exist!
[error] Total time: 0 s, completed Jan 23, 2016 3:13:55 PM
```

**Comment by fommil** [comment]
remove `standardSettings`

**Comment by fommil** [comment]
and probably `foo` as well.

**Comment by vikraman** [comment]
I use `standardSettings` to share common settings between subprojects, and I need to define `foo` to aggregate the subprojects. I updated my test case with some more plugins added to show the issue.

**Comment by fommil** [comment]
this is really better directed at an sbt community, but your config is definitely broken... you shouldn't be calling out to `Defaults.defaultSettings`

what you probably meant to do is override `settings` like we do in `ensime-server` https://github.com/ensime/ensime-server/blob/master/project/EnsimeBuild.scala#L16

and then delete the lines `.settings(standardSettings)`

Note that some things cannot be specified in `override lazy val settings` so you have to have something like you're done (see how we do it)

You also might need to override `rootProject = Some(foo)` to avoid `sbt` from creating one.

**Comment by vikraman** [comment]
That fixes it, thanks!

I think I had picked this up from an old version of scalaz. Also, the sbt docs still mention defining `commonSettings` and adding them in each project.

**Comment by fommil** [comment]
probably your build would fail for other bizarre reasons and give incomprehensible errors, so you'll probably fix some other stuff you thought was unrelated.

**Comment by fommil** [comment]
out of interest, did you need to override `rootProject`? It's not always needed

**Comment by vikraman** [comment]
No, overriding `rootProject` wasn't required.
