### ISSUE TITLE
add -Ymacro-expand:discard on scala 2.11

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#166]
@xeno-by says it means the presentation compiler will try to evaluate macros. Might improve shapeless / etc usage // @rorygraves

**Comment by dwijnand** [comment]
I think I've seen this option be used when compiling the scaladocs.

**Comment by dwijnand** [comment]
* https://github.com/scala/scala/pull/3342
* https://github.com/scalamacros/paradise/issues/61
* https://github.com/scala/async/pull/143
