### ISSUE TITLE
Projects using Dotty fail to compile if ensime-sbt is enabled

### ISSUE THREAD

**Issue by smarter** [ensime/ensime-sbt#169]
https://github.com/smarter/dotty-example-project fails to compile when ensime-sbt is enabled, because ensime-sbt assume that there is an artefact of `scala-compiler`, `scala-library`, `scala-reflect` and `scalap` with version `scalaVersion` which is not true for Dotty. Right now, I think the simplest fix is to use `2.11.5` instead of `scalaVersion` if `scalaVersion` starts with `0.`.

**Comment by fommil** [comment]
actually I have considered this :wink: what you need to do is provide a custom `EnsimeKeys.scalaCompilerJarModuleIDs` for each project.

**Comment by smarter** [comment]
You mean, in the `build.sbt` of each project? Can this be done without depending on `ensime-sbt`?

**Comment by fommil** [comment]
http://ensime.github.io/build_tools/sbt/#customise

**Comment by smarter** [comment]
I don't want to force every project that uses Dotty to depend on ensime-sbt, but this needs to be correct in every project, because people have `ensime-sbt` in their global sbt plugins.

**Comment by fommil** [comment]
the customise docs I linked you to show you how to do that with an autoplugin that you don't commit to the repo.

**Comment by smarter** [comment]
So, every use of dotty and ensime-sbt should add an extra file to every project using dotty that they have? Wouldn't it be simpler to fix this in ensime-sbt?

**Comment by fommil** [comment]
this is definitely a user setting... anybody who uses a custom build of scala needs to do this (e.g. at my work, or anyone with a typesafe subscription). I imagine the list of dotty workarounds is only going to get larger (and if there are enough people using ensime with dotty then it might make sense to make its build depend on `ensime-sbt`)

**Comment by fommil** [comment]
btw, it might actually make sense for dotty to do what scala/scala does, and just provide a custom `.ensime` file.

**Comment by dwijnand** [comment]
As an alternative to setting it in each project I'd recommend creating a global plugin to do the necessary change under the "if scalaVersion starts with 0" condition. If it becomes commonly used within the dotty community it could become it's own standalone plugin.
