### ISSUE TITLE
ensime-sbt not available for newer version of scala

### ISSUE THREAD

**Issue by casertap** [ensime/ensime-sbt#179]
I want to add the akka 2.4.2 dependency to my project but it need scala 2.11+ to work.
Switching my scala version makes ensime-sbt broke because it can not find an ensime-sbt with this version of scala.
https://oss.sonatype.org/content/repositories/snapshots/org/ensime/

Scala is moving toward using the java 8 capabilities in it's version 2.12 which means that I will absolutely want to use the latest version as soon as possible.
Are you planning on updating ensime soon? 
I need to know this before I invest time and effort learning emacs and ensime? 
I am ready to do this but if this means I need to use an old version of scala, this will probably make me change my mind.

**Comment by fommil** [comment]
I think you're doing it wrong. We have 2.11 support. As a polite request, please follow the ensime.org Getting Help page before posting bug reports that don't have a full reproduction.

**Comment by fommil** [comment]
Sbt uses Scala 2.10, just incase that's the confusing bit here.

**Comment by casertap** [comment]
Ok I have setup a repo few days ago to explain my problem to the ensime-vim guys.
https://github.com/casertap/playing-with-actors
I could not make it works, I needed to downgrade all version on this commit to make it works:
https://github.com/casertap/playing-with-actors/commit/77ba3df5ff2d14554fc74cc419caa9ccd0e649bf

Can you explain how can I use akka 2.4.2 with ensime please?
I can not find answers anywhere, sorry

**Comment by casertap** [comment]
I am getting this kind of error:

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.ensime#ensime-sbt;0.4.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          org.ensime:ensime-sbt:0.4.1-SNAPSHOT (scalaVersion=2.12.0-M3, sbtVersion=0.13)
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          org.ensime:ensime-sbt:0.4.1-SNAPSHOT (scalaVersion=2.12.0-M3, sbtVersion=0.13) (/code/ensime_sbt.sbt#L3-4)
[warn]            +- playing-with-actors:playing-with-actors_2.12.0-M3:1.0
sbt.ResolveException: unresolved dependency: org.ensime#ensime-sbt;0.4.1-SNAPSHOT: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
....
[error] (*:update) sbt.ResolveException: unresolved dependency: org.ensime#ensime-sbt;0.4.1-SNAPSHOT: not found
[error] Missing task key: Runs the aggregated UpdateReport for `update' and `updateClassifiers' respectively.
java.lang.IllegalArgumentException
        at org.ensime.CommandSupport$.org$ensime$CommandSupport$$fail(EnsimePlugin.scala:558)
....
error] java.lang.IllegalArgumentException
[error] Use 'last' for the full log.
```

**Comment by fommil** [comment]
You're using snapshot ensime-sbt, please read the build tool setup at ensime.org

**Comment by fommil** [comment]
Why have you created an ensime_sbt.sbt file? That isn't in our documentation anywhere and doesn't do what you think it does.

**Comment by fommil** [comment]
Yes I'm certain that's the problem. I recommend starting again with ENSIME by going to ensime.org, reading the Getting Started page, and making sure you follow the build tool / ensime-sbt steps as prescribed.
