### ISSUE TITLE
support scala's sbt project

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#180]
scala itself now has an sbt build, but I've heard reports that it doesn't work with ensime-sbt. Most likely this is because they are doing terrible things with sbt that are in conflict with many assumptions of ensime-sbt.

It may not be worth the effort to do this, relying instead on a hand-crafted `.ensime` as per http://ensime.org/contributing/scalac but I'm leaving this here incase anybody wants to look at it.

**Comment by fommil** [comment]
@soc says this "just works" and it generates this config (with warnings) https://gist.github.com/soc/dc9fd520ca2c1471a8ae5e3fcd0880ae

**Comment by SethTisue** [comment]
note that the 2.11.x sbt build is now abandoned and no longer worth supporting.

in 2.12.x world, on the other hand, the ant build has been removed and the (now much-improved) sbt build is now required. now that the two builds no longer need to be kept in sync, the door might be open to fix peculiarities in the sbt build if they are causing problems for ENSIME (or other IDEs), depending on what the details are.

**Comment by SethTisue** [comment]
see @fommil's remarks at https://gitter.im/scala/contributors?at=57d05a0d68f483b41cad1b96

**Comment by fommil** [comment]
this is the ticket for 2.12 support https://github.com/ensime/ensime-server/issues/1414

**Comment by fommil** [comment]
after trying this out, I think this might just mean https://github.com/scala/scala/pull/5387 plus generating a `:source-mode t` entry in the `.ensime`

**Comment by fommil** [comment]
or possibly just allowing transformation to add this flag

**Comment by fommil** [comment]
oh, we might also want to exclude the jars of the STARR

**Comment by fommil** [comment]
and can use the transformer to change the version of scala too, working around the scalaVersion debacle.

@dwijnand you may be interested in this

**Comment by dwijnand** [comment]
Only if there's a free burger up for grabs ;-)

**Comment by fommil** [comment]
you'll need to talk to my wife about that :sob:

**Comment by fommil** [comment]
oh, I mean the details... I'll do the work :stuck_out_tongue:

**Comment by dwijnand** [comment]
Copying from scala/contributors on [21st October 2016 8:19 PM](https://gitter.im/scala/contributors?at=580a6a51577f2c227905e2ae)

> I guess a better behaviour for ensime would to pick the most used (because there are sources to compile) scalaVersion, and warn or error if there are others, like sbt plugins in the same build that ensime can't handle

I was considering implementing this in ensime at the next hackday, so it would help out sbt/sbt#2579 too.

WDYT?

**Comment by fommil** [comment]
that'd be cool but I was hoping we could fix the sbt macros! Maybe I'll take that and try a few ideas while you do this.

**Comment by fommil** [comment]
maybe we could introduce `ensimeScalaVersion`, enabling fancy logic like you suggest, but also the ability to override it manually.

**Comment by dwijnand** [comment]
Whatever works that improves this reoccurring issue :)

**Comment by fommil** [comment]
kind of working, tracking what remains in #240
