### ISSUE TITLE
Rename ensime-sbt artefact to sbt-ensime

### ISSUE THREAD

**Issue by soc** [ensime/ensime-sbt#182]
There is tremendous value in having a default naming convention for SBT plugins.
Almost all projects use `sbt-$projectname`, but `ensime-sbt` is the odd one out.

It would be great if this plugin adopted the ecosystem's naming convention!

Related ongoing changes:
 - coursier-sbt-plugin -> sbt-coursier: alexarchambault/coursier#202
 - sbteclipse-plugin -> sbt-eclipse: typesafehub/sbteclipse#314
 - android-sdk-plugin -> sbt-android: https://github.com/scala-android/sbt-android

**Comment by fommil** [comment]
we'll do this when we release 1.0

**Comment by soc** [comment]
Cool, thanks!

**Comment by fommil** [comment]
@soc and what about the generator? `ensimeConfig`? What is consistent?

**Comment by soc** [comment]
@fommil do you have a link to the repo/code?

**Comment by fommil** [comment]
@soc for what?

**Comment by fommil** [comment]
@soc what about `ensimeConfig` instead of `gen-ensime`? I'm making the changes today and hopefully cutting a release. So now is the time to suggest standardisation changes.

**Comment by fommil** [comment]
people can use http://www.scala-sbt.org/0.13/docs/Howto-Running-Commands.html#Define+an+alias+for+a+command+or+task if they want to retain the `gen-ensime` command.

**Comment by fommil** [comment]
hmm, we might need to keep it anyway for the integration tests.

**Comment by fommil** [comment]
@dwijnand @rorygraves thoughts?
