### ISSUE TITLE
unresolved dependency: org.ensime#ensime-sbt;0.5.0: not found

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#193]
In anticipation of the rush of support requests, this is on @soc who insisted that we rename `ensime-sbt` to `sbt-ensime` for consistence in #182.

You're here because you updated the version but not the artefact name.

Also, beware of the leopard.

**Comment by soc** [comment]
Wow, this is some impressive amount of preplanning. :-)

I apologize to everyone who hit this issue, but believe me, I had only the best intentions in mind.

**Comment by fommil** [comment]
Don't worry, nobody reads the documentation or the FAQs so you'll have plenty of time to explain it again and again :-P

**Comment by phillord** [comment]
I'm very impressed.....

**Comment by kqr** [comment]
Wow, thank you. I started reading an old getting started guide, and then once I realised it was old I switched over to the real documentation. I completely missed the transposed words so this was exactly what I needed. Great foresight!
