### ISSUE TITLE
Scalariform custom setting breaks ensimeConfig

### ISSUE THREAD

**Issue by jodersky** [ensime/ensime-sbt#197]
Using a non-boolean (or Int) setting in Scalariform throws a MatchError from `ensimeConfig`.

## Steps to reproduce
1. Add following Scalariform settings to a project's settings

    ```scala
    ScalariformKeys.preferences := ScalariformKeys.preferences.value
      .setPreference(DanglingCloseParenthesis, Preserve)
                                               ^^^
                                               notice the non bool or int value
    ```

2. Run `sbt ensimeConfig`

3. Watch it die with a `MatchError`

## Underlying issue
The part that generates the contents of the `.ensime` configuration file, `SExpFormatter` has a non-exhaustive match, [as highlighted here, on lines 745-749](https://github.com/ensime/ensime-sbt/blob/068b5efb47878802abb486cdb4930564d708f194/src/main/scala/EnsimePlugin.scala#L745-L749)

The fix is probably pretty simple, however since the `.ensime` configuration file is also read from the server, I wanted to post an issue before submitting a PR.

**Comment by jodersky** [comment]
Hmm this bug looks deeper than I thought.
In the build configuration it says:
```scala 
// intentionally old version of scalariform: do not force an upgrade upon users
libraryDependencies += "org.scalariform" %% "scalariform" % "0.1.4",
```
and `Preserve` and other Intents don't exist in that scalariform version yet. To make things worse, it seems that an upgrade cannot occur until #148 has been fixed, which itself requires an upstream fix.

**Comment by fommil** [comment]
We need to use an old version of scalariform for backwards compatibility so I'm not sure we can accept a fix. For now you have to remove these settings from your config. When we release 1.0 and look at breaking api changes for 2.0 we should probably move to preferring a config file reference, rather than parsing the parameters. Or just move over to scalafmt wholesale.

**Comment by jodersky** [comment]
I didn't know about scalafmt, it looks awesome :) Btw, I submitted a workaround for this issue
