### ISSUE TITLE
invoke ensime-server to index a project

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#199]
following on from https://github.com/ensime/ensime-server/pull/1447 it would be good to be able to programmatically index a project. i.e. given a `.ensime` file and a version of `ensime-server`, do the indexing. #196 would help a lot.

**Comment by fommil** [comment]
this absolutely needs to do resolution lazily, otherwise the cost to the user's project build will be too high.

**Comment by fommil** [comment]
after discussion with @dwijnand I think we should abandon all hope of implementing this. It would add a sonatype resolver to the user's project (not good) and also involve a lot of code duplication with the client. Either the build tool plugin or the client should own this code, and since the clients already have it, it doesn't make sense to try and make the build tools have it as well.

Therefore I suggest moving this as a client side feature and if people want to invoke indexing as part of an automated workflow, then they can call emacs / whatever in batch mode.

**Comment by dwijnand** [comment]
What about avoiding resolvers and the like and using coursier programmatically?

**Comment by fommil** [comment]
Then we'd be adding a coursier dependency

**Comment by dwijnand** [comment]
Make it a new autoplugin or SBT project or separate repo and leave the current one as is.
