### ISSUE TITLE
don't set libraryDependencies for scala and dotty

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#200]
if the project name is `scala` or `dotty`, use Odersky mode and don't populate the `libraryDependencies`

**Comment by smarter** [comment]
I'm using ensime with dotty without any hack and it just works, not sure why this would be needed

**Comment by smarter** [comment]
The only thing we wish for from ensime is to get https://github.com/ensime/ensime-sbt/issues/169 fixed, but I'm not holding my breath :).

**Comment by fommil** [comment]
@smarter oh, I think it's the same thing.

**Comment by fommil** [comment]
@smarter this is easy, I can pick it up today if I get the time.

**Comment by fommil** [comment]
@smarter I've got a reproduction, should be easy to workaround now.

**Comment by fommil** [comment]
ok, I'm done for the day, but there is a repro and a failed attempt to fix it in https://github.com/fommil/ensime-sbt/tree/odersky-mode

**Comment by smarter** [comment]
That might be the way to go for fixing scala/scala, but for dotty the issues is with projects that compile with dotty, not with the dotty project itself which has `scalaVersion := 2.11.5`.

**Comment by milessabin** [comment]
Are you saying that the "odersky mode" branch is also a fix for working on scala/scala?

**Comment by fommil** [comment]
@milessabin "odersky mode" is traditionally for legacy reasons scala/scala until we get further evidence of an upstream Odersky requirement.

**Comment by fommil** [comment]
@smarter yeah, give us a presentation compiler and then we can talk ;-)

**Comment by fommil** [comment]
@milessabin 0.5.1 is on its way to maven central
