### ISSUE TITLE
use scalaOrganisation

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#203]
everywhere we have `"org.scala-lang"` we should probably use the `scalaOrganiZation` (sic) setting.

**Comment by yyadavalli** [comment]
When changed to use `scalaOrganization.value` the output from `ensimeConfig` has the new organization but the output from `ensimeConfigProject` still has `org.scala-lang`, is this expected or am I missing something

**Comment by fommil** [comment]
Yeah, I'd say so. Sbt has its own Scala version.
