### ISSUE TITLE
Plugin version 0.1.3 not available

### ISSUE THREAD

**Issue by markschaake** [ensime/ensime-sbt#21]
When trying to install via directions on the README, SBT fails to find the plugin version 0.1.3.

```
addSbtPlugin("org.ensime" % "ensime-sbt-cmd" % "0.1.3")
```

does not work. This does:

```
addSbtPlugin("org.ensime" % "ensime-sbt-cmd" % "0.1.2")
```

Is this a documentation error? Or a failure to publish?

**Comment by Sarrouna** [comment]
I have a self-contained application in SBT. My data is stored on HDFS (the hadoop file system).How can I get a jar file to run my work on another machine.
The directory of my project is the following:

/MyProject
   /target
        /scala-2.11
                 /MyApp_2.11-1.0.jar
   /src
      /main
           /scala

	
I want to get my jar file or how to copy it in my local disc.

**Comment by fommil** [comment]
@sarrouna sure, just feel free to ignore all the documentation we've written, and while you're at just go and comment on a completely unrelated github ticket from 2 years ago. Honestly, it'll be grand. Go you.
