### ISSUE TITLE
Cannot build a project when `ensime-sbt` plugin is enabled

### ISSUE THREAD

**Issue by ktonga** [ensime/ensime-sbt#210]
It's happening with [Scalding](https://github.com/twitter/scalding) as far I can tell. When I try to build the project (`sbt scalding-core/compile`) and the plugin is enable (globally in my case) the build fails with the following errors:

```
[error] (scalding-serialization/*:update) java.lang.IllegalArgumentException: Cannot add dependency 'org.scala-lang#scala-compiler;2.11.7' to configuration 'ensime-internal' of module com.twitter#scalding-serialization_2.11;0.16.1-SNAPSHOT because this configuration doesn't exist!
[error] (scalding-args/*:update) java.lang.IllegalArgumentException: Cannot add dependency 'org.scala-lang#scala-compiler;2.11.7' to configuration 'ensime-internal' of module com.twitter#scalding-args_2.11;0.16.1-SNAPSHOT because this configuration doesn't exist!
[error] (scalding-date/*:update) java.lang.IllegalArgumentException: Cannot add dependency 'org.scala-lang#scala-compiler;2.11.7' to configuration 'ensime-internal' of module com.twitter#scalding-date_2.11;0.16.1-SNAPSHOT because this configuration doesn't exist!
[error] (maple/*:update) java.lang.IllegalArgumentException: Cannot add dependency 'org.scala-lang#scala-compiler;2.11.7' to configuration 'ensime-internal' of module com.twitter#maple;0.16.1-SNAPSHOT because this configuration doesn't exist!
[error] (scalding-core/*:projectDescriptors) java.lang.IllegalArgumentException: Cannot add dependency 'org.scala-lang#scala-compiler;2.11.7' to configuration 'ensime-internal' of module com.twitter#scalding-args_2.11;0.16.1-SNAPSHOT because this configuration doesn't exist!
```

I double checked and if I disable `ensime-sbt` in global plugins it doesn't happen anymore.

I don't know what the actual problem is, but I think that a plugin such as `ensime-sbt`, which is  supporting/tooling related, should never prevent a project from being built. Maybe emitting a warning, event for fatal errors, may be more appropriate for a plugin that should be kinda passive.

**Comment by fommil** [comment]
It's almost certainly going to be a problem in scalding.

**Comment by fommil** [comment]
Minimise the problem and send a PR with a failing test.

**Comment by fommil** [comment]
reproduced. Weird. The config isn't being added for some reason.

**Comment by fommil** [comment]
yup, bug in scalding build, they shouldn't be using the `Project` constructor https://gitter.im/sbt/sbt?at=57643feaf0528c4c5bb9f6ee

**Comment by ghost** [comment]
Hi,

I'm having the same issue in https://github.com/spotify/scio  Would you mind explaining how this would be fixed in the source repo?
