### ISSUE TITLE
change .ensime format: modules have scala ivy configs

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#217]
to support https://github.com/ensime/ensime-server/issues/1152 and https://github.com/ensime/ensime-emacs/issues/498 the `.ensime` file needs to move the scala compiler flags from the main section into each module section, and each module section needs to be split up by configuration name.

**Comment by fommil** [comment]
this will probably involve changing `ensimeJavacOptions` / `ensimeScalacOptions` (and maybe others) to be scoped to a config instead of just per-project.

**Comment by yyadavalli** [comment]
From gitter for future reference

> an example format I was thinking of: `:projects ((:name "bar" :configs ((:config "compile" :depends ("foo" "test") :target "" ...etc...)  (:config...))) ...)`

**Comment by fommil** [comment]
or maybe the name and config should both be top level and config could be optional.

**Comment by fommil** [comment]
some tidying up to do, but we're well on our way
