### ISSUE TITLE
press enter to interrupt --- doesn't work

### ISSUE THREAD

**Issue by krux02** [ensime/ensime-sbt#218]
### Steps to reproduce
1. M-x sbt-start
2. ~compile
3. press enter
### Expected behaviour

sbt should interrupt the build
### Actual behaviour

<nothing happens>

**Comment by fommil** [comment]
you probably meant to raise this against `emacs-sbt-mode`.

we don't recommend use of `~compile`. Prefer a file save hook, it's far more efficient.

**Comment by krux02** [comment]
Yes you are right I meant to raise it for `emacs-sbt-mode`. All those different packages can be a bit confusing when you are new, but when I think about it now it makes sense.

For your recommendation, it doesn't really help me much, because I don't know how to do a save hook in emacs yet. I am now to emacs, and honestly it sounds like a lot of work. On the other hand I am already used to the `~command` pattern it works, and the bottleneck is not file system change watching.

**Comment by fommil** [comment]
@krux02 have a look at recent discussions about this on this tracker @VlachJosef is writing it up

**Comment by krux02** [comment]
@fommil which tracker do you mean?

**Comment by VlachJosef** [comment]
@krux02 I believe @fommil meant this issue https://github.com/ensime/emacs-sbt-mode/issues/51 It was little different issue than yours problem, but in the end it boils down to usage of `~`.

Which seems like I should hurry up with writing that part of a documentation.

**Comment by fommil** [comment]
I'd like to have some nice convenience methods for accessing the .ensime file (with buffer local caches). It would be really useful and efficient in my workflow, for example, to delete the jar file associated to a source file on save.
