### ISSUE TITLE
Generating `.ensime` for multiprojects using sbt-android fails…

### ISSUE THREAD

**Issue by michalrus** [ensime/ensime-sbt#224]
### Steps to reproduce
1. Clone https://github.com/michalrus/ensime-sbt-issue-224
2. Run `sbt ensimeConfig` in the cloned directory.
### Expected behaviour

The generated `.ensime` file should mention `${ANDROID_SDK_HOME}/platforms/android-23/android.jar`.
### Actual behaviour

There’s no link to `android.jar` and therefore, in Emacs, all uses of `android.*` symbols are not found and colored in red.

---

What’s interesting: when you checkout the `single-project` branch—while the default one, where this issue is observable, is `multi-project`—and run `ensimeConfig` on a single project… `android.jar` gets into `.ensime` this time:

``` elisp
[…]
 :java-compiler-args ("-bootclasspath"
    "/nix/store/wmr8fs3qm6darwfixs0f8agsb9jki57s-android-sdk-25.1.7/libexec/platforms/android-23/android.jar"
    "-g")
[…]
 :compiler-args ("-bootclasspath"
    "/nix/store/wmr8fs3qm6darwfixs0f8agsb9jki57s-android-sdk-25.1.7/libexec/platforms/android-23/android.jar"
    "-javabootclasspath" "-feature" "-deprecation"
[…]
```

**Comment by fommil** [comment]
Interesting. I think I've heard of something similar before. The workaround is to use the transforming task to add whatever jars you need. Word you be interested in helping to fix this bug?

**Comment by pfn** [comment]
We've seen this before, workaround:

``` scala
dependencyClasspath in Compile ++= bootClasspath in Android in oneOfTheAndroidSubProjects
```

**Comment by fommil** [comment]
You can do this without modifying your project's sbt build by updating the EnsimeConfig with a transformer.

**Comment by michalrus** [comment]
Thank you both for taking interest in this!

@fommil, sure, I’d be happy to help. What do I do first?

@pfn, thank you for the suggestion! Do you mean:

``` diff
diff --git a/build.sbt b/build.sbt
index b1ec236..202a0f1 100644
--- a/build.sbt
+++ b/build.sbt
@@ -1,6 +1,7 @@
 scalaVersion in ThisBuild := "2.11.8"

 lazy val AndroidSettings = android.Plugin.androidBuild ++ Seq(
+    dependencyClasspath in Compile ++= (bootClasspath in Android).value,
     platformTarget in Android := "android-23"
   )

```

or:

``` diff
diff --git a/build.sbt b/build.sbt
index b1ec236..6f2c115 100644
--- a/build.sbt
+++ b/build.sbt
@@ -1,5 +1,7 @@
 scalaVersion in ThisBuild := "2.11.8"

+dependencyClasspath in Compile ++= (bootClasspath in Android in core).value
+
 lazy val AndroidSettings = android.Plugin.androidBuild ++ Seq(
     platformTarget in Android := "android-23"
   )
```

or:

``` diff
diff --git a/build.sbt b/build.sbt
index b1ec236..40eeda6 100644
--- a/build.sbt
+++ b/build.sbt
@@ -5,6 +5,9 @@ lazy val AndroidSettings = android.Plugin.androidBuild ++ Seq(
   )

 lazy val root = Project(id = "root", base = file("."))
+  .settings(
+    dependencyClasspath in Compile ++= (bootClasspath in Android in core).value
+  )
   .aggregate(core)

 lazy val core = Project(id = "core", base = file("core")).settings(
```

…? I’ve tried all three without success. :crying_cat_face:

**Comment by michalrus** [comment]
@fommil, could you point me to a resource/sample code/… on transformers?

> `site:ensime.org transformer` - did not match any documents

---

Edit: found it → https://github.com/ensime/ensime-sbt/blob/2.0/src/sbt-test/sbt-ensime/config-transformation/build.sbt.

**Comment by michalrus** [comment]
OK, this one works, but it’s… a bit silly.

``` diff
diff --git a/build.sbt b/build.sbt
index b1ec236..49149a8 100644
--- a/build.sbt
+++ b/build.sbt
@@ -5,6 +5,10 @@ lazy val AndroidSettings = android.Plugin.androidBuild ++ Seq(
   )

 lazy val root = Project(id = "root", base = file("."))
+  .settings(
+    javacOptions in Compile := (javacOptions in (core, Compile)).value,
+    scalacOptions in Compile := (scalacOptions in (core, Compile)).value
+  )
   .aggregate(core)

 lazy val core = Project(id = "core", base = file("core")).settings(
```

**Comment by fommil** [comment]
is this still considered a bug in ensime-sbt or is it a problem with the android projects?

**Comment by fommil** [comment]
btw you don't need to mutate `javacOptions` or `scalacOptions` just to affect ensime, we have keys such as `ensimeAdditionalCompilerArgs`

**Comment by pfn** [comment]
An issue for ensime to solve

Or at least documented for android projects.

**Comment by fommil** [comment]
I think we'll go with "document for Android projects". Can one of you please try the above using:
1. `ensimeAdditionalCompilerArgs` instead of `scalacOptions in Compile`

and I'll create an extra parameter for you to specify the java args.

Note I may rename `ensimeAdditionalCompilerArgs` to `ensimeAdditionalScalacArgs` in the next release. I'll use android as the example of how to use these flags, it's what they are designed for.

**Comment by fommil** [comment]
docs added here, http://ensime.org/build_tools/sbt/#customise

I'm assuming it works unless you tell me otherwise. I don't see why it wouldn't

**Comment by michalrus** [comment]
Works for me!
