### ISSUE TITLE
scalariform format one file

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#227]
a good addition to EnsimeExtras would be the ability to format one source at a time with scalariform. This would allow us to complete https://github.com/ensime/ensime-server/issues/1606 and then perhaps move to `scalafmt` in the future (possibly a patch to sbt-scalarform would be appropriate too).

**Comment by yyadavalli** [comment]
Hi, I'd like to pick this up if anyone else is not working on it

**Comment by fommil** [comment]
yeah, that'd be cool! I think @sugakandrey was going to look at it in a few weeks, but you can certainly pick it up and if we don't hear from you, Andrey can pick it up again :smile:

**Comment by fommil** [comment]
there is already some logic in `ensimeCompileOnly` that could be reused to discover if a source file really belongs to a `Project`.

**Comment by yyadavalli** [comment]
Sure, actually I looked at the code in `ensimeCompileOnly` but I did not think all those checks were necessary, I am thinking of putting in checks to see if the file exists and is a `.scala` file.
Does it matter if the file belongs to the Project or not?

**Comment by fommil** [comment]
Yes, definitely important.

**Comment by fommil** [comment]
Otherwise you could apply the settings of the wrong project. Failing is far more preferable.
