### ISSUE TITLE
.ensime not generated correctly in the presence of subprojects

### ISSUE THREAD

**Issue by mikesperber** [ensime/ensime-sbt#233]
### Steps to reproduce
1. Check out `https://github.com/mikesperber/ensime-multi-project` 
2. `cd bar`
3.  `sbt ensimeConfig`
### Expected behaviour

An `.ensime` file that contains the `bar` project under `:subprojects`, so that files from it could be recognized.
### Actual behaviour

Only `foo` is listed under `:subprojects`.

**Comment by fommil** [comment]
I'm not sure this is a valid multi-project. Ask for sbt help to get this setup, and if you want to see examples of valid multi-project builds, look at ensime-server.

In any case, a restriction of ensime is that all subprojects must have a common root directory, so the clients wouldn't be able to support this even if .ensime contained the projects you expect.

**Comment by fommil** [comment]
although, you could move the .ensime to the parent because that's the common dir. Still, I'm not convinced this is a valid/canonical multi project build, let's open it up again if the sbt people say that it is.

**Comment by fommil** [comment]
@dwijnand what are your thoughts on the validity of the referenced project?

**Comment by dwijnand** [comment]
I wouldn't call it canonical, rather pretty niche.

I guess if it works in sbt, then it's a fringe-case ensime doesn't currently support.

**Comment by fommil** [comment]
is this way of doing it likely to be removed in 1.0? Should it be? I thought 1.0 was a way of clearing up non-canonical ways of doing things.

**Comment by dwijnand** [comment]
No. Dunno. That is true, just this one isnt promenant.

**Comment by fommil** [comment]
ok, well in that case we'll close this as WontFix but would accept a PR to fix it from @mikesperber if it isn't too complex. Happy to show you how to get set up to contribute to this plugin if you'd like to dive in.

**Comment by mikesperber** [comment]
Well, there's this:

http://stackoverflow.com/questions/11653435/how-to-reference-external-sbt-project-from-another-sbt-project

I have several projects that live side-by-side with a common subproject, so putting the subproject in a subdirectory of the main project won't work. And the SBT setup for this works just fine.

I'd be happy to give fixing it in ENSIME a shot.

**Comment by fommil** [comment]
probably the best thing to do first is to read http://ensime.github.io/build_tools/sbt/#contributing

Then put your example project above into the `src/sbt-test` structure of the other scripted tests, following the pattern of other simple tests, and put a bunch of printlns into the EnsimePlugin and see what is happening and where the `foo` / `bar` is getting dropped.

Note that in the various ensime editors, you'll need to move the `.ensime` up one directory or they won't be able to reconcile the sources you have with the `.ensime` containing their config. You could probably do that as a local post-Task command.

**Comment by mikesperber** [comment]
Just a note: I changed the example repo at:

[https://github.com/mikesperber/ensime-multi-project](url)

... to put the subproject in a subdirectory, and it still fails - i.e. only the subproject gets included in ENSIME's list.

However, I've noticed that this is tied to the format of the `build.sbt` in the subdirectory: If I change `bar/foo/build.sbt` to bare format, the `.ensime` file is generated correctly.

**Comment by fommil** [comment]
this could be a bug with your setup, btw are you sure `file(".")` is relative to the file and not the starting directory of sbt?

**Comment by mikesperber** [comment]
I don't follow, I'm afraid. `file(".")` is what it says in the docs:

http://www.scala-sbt.org/0.13/docs/Multi-Project.html

What else should I put there?

**Comment by fommil** [comment]
did you get any further with this? If you've given up, we could just close it

**Comment by mikesperber** [comment]
For now, I've given up I'm afraid ... Just not enough time. So feel free to close!
