### ISSUE TITLE
sbt 1.0 compatibility

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#237]
- [x] For the sake of 1.0 compatibility, we should remove our use of deprecated APIs.
- [ ] normalise the sbt jars in the tests
- [x] remove deprecated apis from tests (Build projects, swap ensime-server for smaller tests)
- [x] convert ensimeConfig et al to a Task

**Comment by yyadavalli** [comment]
Are we planning to move the build to use `.sbt` format, I believe `Build` is deprecated currently

**Comment by fommil** [comment]
in the build files, yes. That can be done now.

in our plugin, no it still needs to be written in .scala... but we'd use the macro api instead of the .map/.flatMap api. but until we can fix how the presentation compiler handles macros, that would dramatically slow me down because we'd lose ensime support.

**Comment by fommil** [comment]
(btw, this ticket is about publishing a 1.0 compatible jar, not just _using_ sbt to build our plugin)

**Comment by yyadavalli** [comment]
I know, just thought about if we are going to use it

**Comment by fommil** [comment]
that'd definitely be nice, I've been putting it off for a long time. I also plan to build the sensible settings stuff as a plugin... I end up copy/pasting it everywhere.

**Comment by fommil** [comment]
blocked by https://github.com/sbt/sbt/issues/2829

**Comment by fommil** [comment]
the biggest thing we could do would be to use `Task` instead of `Command`

**Comment by fommil** [comment]
I am ok with removing `ensime-server` from the test suite. Although it is exercising some things that need a separate test (from memory, there may be more)

- [x] unusual inter-test dependencies (`it` depending on a `test`)
- [x] user-provided source zips

**Comment by fommil** [comment]
https://github.com/dwijnand/sbt-compat

**Comment by MasseGuillaume** [comment]
It's now available: http://repo1.maven.org/maven2/org/ensime/sbt-ensime_2.12_1.0/

`addSbtPlugin("org.ensime" % "sbt-ensime" % "2.0.1")`
