### ISSUE TITLE
depends-on logic for new format

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#247]
as discussed in #245

**Comment by fommil** [comment]
@yyadavalli we can't forget about this before doing much more on the server side...

**Comment by fommil** [comment]
the ensime-server example project should have two interproject dependencies in it that aren't working right now: server's tests depend on core's test (same for the integration tests).

It should also be relatively easy to have a new multi-project test project that has something similar, will make it a lot quicker to test.

**Comment by yyadavalli** [comment]
@fommil sure, I'll try to do it this weekend. I might already have a test like that lying around.
