### ISSUE TITLE
stop trying to be too smart

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#249]
thanks to @dragos https://github.com/fommil/imaginary-friend/issues/18

**Comment by dwijnand** [comment]
I think no-adapt-args is both a smart and a sensible setting..

**Comment by fommil** [comment]
It seems to break the pc though

**Comment by dwijnand** [comment]
.. for co-smart, co-sensible people that want the compiler to adapt their args :)

**Comment by dragos** [comment]
It doesn't really "break" the PC, it just looks like that because it's adding these arguments to the PC but not the build itself. It would fail in the same way in the batch compiler, should you pass that argument, of course.

**Comment by fommil** [comment]
Ah, of course.
