### ISSUE TITLE
lots of things need to use the correct config

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#250]
e.g. `ensimeUnmanagedSourceArchives` needs to restrict to the `config`.

**Comment by fommil** [comment]
and they need to be called for `Compile`

**Comment by dwijnand** [comment]
Rule of thumb: anything filepath-based (including transitively) needs to specify project and config. Sadly.

**Comment by fommil** [comment]
Yeah that's OK, but to annoying thing is that there is no way to define tasks for user generated phases

**Comment by dwijnand** [comment]
What's a phase?

**Comment by fommil** [comment]
Config
