### ISSUE TITLE
scalariform in custom test phases

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#251]
`ensimeScalariformOnly` is not added to all the user's test configurations, we hard code `Test` and `Compile`.

We need a way of being able to attach this config onto all configs.

Maybe we should just make this project-level rather that `(project,config)` level.

@dwijnand any thoughts? It's basically https://github.com/sbt/sbt/issues/2534 isn't it? :confounded:

**Comment by dwijnand** [comment]
Yep. See if moving to project-level works.

**Comment by fommil** [comment]
unfortunately that workaround won't do for the `compileOnly` task as classpaths are important
