### ISSUE TITLE
org.ensime and others missing after following SBT install guide

### ISSUE THREAD

**Issue by luisgerhorst** [ensime/ensime-sbt#258]
After follwing the [install section of the SBT guide](http://ensime.github.io/build_tools/sbt/#install) `~/.ivy2/cache/org.ensime/` and several other subfolders of `~/.ivy2/cache` were missing which caused the following error when running `M-x ensime`:

```
Error: Could not find or load main class org.ensime.server.Server
```

Several `org.ensime` paths were included in the classpath thought. Deleting `~/.ivy2` and rerunning `sbt` in the project did not help. Running `M-x ensime-server-update` added several new subdirectories to `~/.ivy2/cache` (including `org.ensime`) and resolved the issue. I've got `sbt` 0.13.13, Scala 2.11.8, JDK 1.8.0_112, macOS 10.12.1 and Emacs 25.1.1. Sorry for not using the template.

**Comment by fommil** [comment]
Can you please give a reproduction in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also a good starting point. We are more than happy to help you turn it into an automated test, and discuss ideas on how to fix it. Read the http://ensime.org/contributing guide for more information.

We close tickets that look like a known issue or don't provide the details requested by the template, but it's not the end of the conversation and we will open it up again when there is enough information to go on. This is to improve the quality of our issue tracker and to make it easier for contributors to help.

We will reopen this ticket if you can confirm it is a bug by giving us a **detailed** reproduction. Please read the http://ensime.org/getting_help guide to understand the steps that are required prior to submitting a bug report.

**Comment by luisgerhorst** [comment]
No problem, I'm sorry but I currently don't have the time to put that much effort into this. Just wanted to dump this in here and maybe it helps someone.

**Comment by fommil** [comment]
it's sounds like you should have just followed the troubleshooting guide. This is the no. 1 issue.

**Comment by luisgerhorst** [comment]
Ah I see, I somehow did not get to it since I was only looking at `sbt` troubleshooting guide and FAQ. Thanks!

**Comment by fommil** [comment]
it can sometimes be difficult to find the right component, but a good rule of thumb is that it's the emacs side that has gone wrong unless you have dug deeper and know exactly which component is broken and can write a test case proving it.
