### ISSUE TITLE
support typelevel scala

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#259]
a dependency of https://github.com/ensime/ensime-emacs/issues/549

- needs a test
- might be hit by regressions in sbt 0.13.13 #254 
- needs to add the scala organisation to the `.ensime`

requested by @raulraja

I'd be happy to help but this is way beyond my sbt foo --- it involves ivy configurations and so on.

**Comment by milessabin** [comment]
Can you say something about what's not working/needs to be done?

**Comment by fommil** [comment]
If somebody could write a test for a simple project that uses typelevel scala, then we'll have a good idea. We use standard scripted tests, documented under our contributing page.

**Comment by raulraja** [comment]
I'll work on one tomorrow that shows the issue I encountered. Thanks for
the interest on addressing this.

**Comment by fommil** [comment]
I just had deju vu and then realised that we did this already https://github.com/ensime/ensime-sbt/tree/2.0/src/sbt-test/sbt-ensime/different-scalaorganization

It might be that you need to make sure you use scalaOrganisation in ThisBuild. This might just be an Emacs side issue.

**Comment by fommil** [comment]
#260 might be the best way to proceed

**Comment by raulraja** [comment]
@fommil @milessabin confirmed that it works with `scalaOrganization in ThisBuild := "org.typelevel"`. 
@fommil Is this part of the issues related to multi-module projects? Feel free to close this one if unrelated to the `scalaOrganization`.

**Comment by fommil** [comment]
I'm surprised it works on the client side! I think #260 will solve this properly because right now if you look in your classpath file you'll see a bunch of typesafe jars in there, not typelevel.

`in ThisBuild` is the right thing to do for anything that's project-wide, so that's not a bug. But if you could update the sbt-ensime docs to use this as an example of using typelevel scala that would be appreciated.

I was planning on hacking on #260 at the next hack day, which is in about a month. If you know anybody interested in a little bit of coding using coursier, I could put together a branch for them.
