### ISSUE TITLE
use coursier to resolve scala and ensime-server

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#260]
If we define tasks that return File for the scala/ensime jars,  we could remove our ivy mess/hacks and remove a bunch of work from the clients.

The implementation of those tasks could be in a separate autoplugin so people behind corporate firewalls could implement their own and not depend on coursier.

@alexarchambault this code unfortunately is java 6. Have you abandoned that branch? It would be really great if you could please nudge it along.

**Comment by fommil** [comment]
@pascr when this is done, you could look into implementing/simplifying the atom code

**Comment by fommil** [comment]
WIP https://github.com/fommil/ensime-sbt/tree/coursier

**Comment by fommil** [comment]
this is coming along much better than I could have expected, I think it works in my branch. Just going through all the test assertions (with a big change like this, it's lots of changes...)

https://github.com/fommil/ensime-sbt/tree/coursier

**Comment by fommil** [comment]
@raulraja btw, getting scala org support this way is pretty trivial

**Comment by raulraja** [comment]
Looking forward to try it out!

**Comment by fommil** [comment]
I'm hoping to have this ready sometime on Saturday, but not promising anything because I have a trip to the Mun planned :wink:  http://wiki.kerbalspaceprogram.com/wiki/Mun
