### ISSUE TITLE
Setting ensimeScalaVersion as instructed in doc fails

### ISSUE THREAD

**Issue by asarkar** [ensime/ensime-sbt#261]
http://ensime.github.io/build_tools/sbt/
> ensimeScalaVersion := "2.11.8"

Reality:
```
<path to project>/project/ensime.sbt:1: error: not found: value ensimeScalaVersion
ensimeScalaVersion := "2.11.8"
```

**Comment by fommil** [comment]
Not in the project dir.

And please, read the troubleshooting guide. Raising a ticket is not your first point of contact.

**Comment by asarkar** [comment]
@fommil Doc says in the project dir.

> Simply create an ensime.sbt in the project directory.

**Comment by fommil** [comment]
Then send a pr to the doc page.

**Comment by fommil** [comment]
Should probably say "in your project's base directory"

**Comment by asarkar** [comment]
Gladly, if I know where the page is. Sorry, just getting started with Atom and Ensime.

**Comment by fommil** [comment]
Every page has an edit button at the bottom. Please use gitter next time you hit an issue, we don't use the issue tracker for support.

**Comment by asarkar** [comment]
Done, and thanks for the help. Will use gitter next time, like I said, just getting started.
https://github.com/ensime/ensime.github.io/pull/185
