### ISSUE TITLE
 Could not open JAR file "org.eclipse.jdt.core-3.10.0-sources.jar"

### ISSUE THREAD

**Issue by bollmann** [ensime/ensime-sbt#266]
I just installed the latest (unstable) ensime package `20161110.1316` from the emacs melpa repository. After adding the plugin to `~/.sbt/0.13/plugins/plugins.sbt` as
```[scala]
addSbtPlugin("org.ensime" % "sbt-ensime" % "1.11.3")
```
I can run the `sbt ensimeConfig` command to create my project's `.ensime` file. Part of the dependencies being downloaded is the jar `org.eclipse.jdt.core-3.10.0-sources.jar` from maven. However, this jar is completely empty, as you can check upstream here:  https://repo1.maven.org/maven2/org/eclipse/jdt/org.eclipse.jdt.core/3.10.0. (The `org.eclipse.jdt.core-3.10.0-sources.jar` is empty)

This empty sources JAR then leads to ensime mode not working properly inside emacs. More specifically, when I try to connect to the ensime server with `ensime`, it fails saying that the above jar file is empty and thus corrupt.

Has anyone encountered this issue before? Why does ensime mode depend on the empty eclipse JDT jar?

**Comment by fommil** [comment]
Troubleshooting guide
