### ISSUE TITLE
Confirm/fix path to tools.jar

### ISSUE THREAD

**Issue by ches** [ensime/ensime-sbt#289]
See #286—since that merge `tools.jar` is in `:ensime-server-jars` in `.ensime` but its path there is `JAVA_HOME/tools.jar`. On my Oracle JDK installs on OS X (1.7 and 1.8), it's actually at `JAVA_HOME/lib/tools.jar` (yes, yes, look at all that non-libre software 😇).

Trivial fix if the missing `lib` path component was indeed a mistake, I just need a minute to verify if the location is consistent across platforms/JDKs. @fommil what's your environment?

**Comment by fommil** [comment]
I'm just an idiot... it's lib/tools.jar here. I'll fix and release .4 tonight. Thanks for the report!
