### ISSUE TITLE
Java formatter

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#291]
TIL https://github.com/typesafehub/sbt-java-formatter

Could power an ensimeFormatOnly for .java files

We need to be real careful about licenses. If it depends on the maven/eclipse formatter it introduces EPL code into the build.

Closes https://github.com/ensime/ensime-server/issues/1402

@ktoso

**Comment by ktoso** [comment]
Yeah it pulls in the eclipse formatter AFAIR.
We have not yet used it much btw, but feel free to use.

**Comment by fommil** [comment]
@ktoso possibly not, the EPL is explicitly incompatible with the GPL. But it might be ok because our sbt plugin is Apache 2.0. But I wouldn't want to force that on users, since it restricts their freedom. Nevertheless, this ticket belongs here. Feel free to unsubscribe if it's not of interest.
