### ISSUE TITLE
Failed to download coursier ensime server

### ISSUE THREAD

**Issue by gargsharad** [ensime/ensime-sbt#309]
Failed to download coursier ErrorClass {message: "Response code 404 (Not Found)", host: "git.io", hostname: "git.io", method: "GET", path: "/v2L2P"…}host: "git.io"hostname: "git.io"message: "Response code 404 (Not Found)"method: "GET"name: "HTTPError"path: "/v2L2P"stack: (...)get stack: stack()set stack: stack()statusCode: 404statusMessage: "Not Found"__proto__: Error
Unhandled promise rejection Promise with error: ErrorClass

and actually http://git.io/v2L2P  do return 404

which is causing the Failed to download coursier
Exit code: HTTPError: Response code 404 (Not Found) 
and ensime server is not starting

**Comment by gargsharad** [comment]
I am an entry level Atom user but this caused 3 fresh reinstalls of atom and ensime

**Comment by fommil** [comment]
This is not the correct repo, please follow instructions on the website.
