### ISSUE TITLE
Overriding ensimeResolvers

### ISSUE THREAD

**Issue by kbrowder** [ensime/ensime-sbt#310]
Hi, trying to use this behind a corporate firewall with limited access to the outside world.  We've got a maven proxy that has access, but I can't get ensime to use my repository file, I think this is because ensime has hardcoded urls.

### I tried

EnsimeCoursierKeys.ensimeResolvers := Seq(
    coursier.MavenRepository("http://my-proxy/content/groups/public/")
    )

### Expected behaviour

Gets ensime from the proxy

### Actual behaviour

Continues to search oss.sonatype.org.

Any ideas?

**Comment by fommil** [comment]
try adding `... in ThisBuild := Seq(...)`.

BTW, I use this approach http://ensime.org/contributing/#manual-qa-testing with the jars from http://ensime.typelevel.org/

**Comment by fommil** [comment]
double documented http://ensime.org/build_tools/sbt/#customise

**Comment by fommil** [comment]
hmm, I used to have this under a section called "Behind a Corporate Firewall". If you send a pr to the docs to bring that back, I'd merge it.

**Comment by kbrowder** [comment]
Hmmm, I missed those somehow.
Any idea if there's a way to not specify the exact file?  We have all this wonderful machinery for resolving dependencies and it'd be nice to not have to throw that away in this case.

**Comment by kbrowder** [comment]
I think I almost have it in a some common properties (so implicitly in ThisBuild):
```scala
    ensimeResolvers := Seq(
      coursier.MavenRepository("http://my-proxy/content/groups/public/")),

    ensimeScalaJars := resolveScalaJars(scalaOrganization.value, ensimeScalaVersion.value)(ensimeResolvers.value),
    ensimeScalaProjectJars := resolveScalaJars("org.scala-lang", sbtScalaVersion)(ensimeResolvers.value),
    ensimeServerJars := resolveEnsimeJars(scalaOrganization.value, ensimeScalaVersion.value, ensimeServerVersion.value)(ensimeResolvers.value),
    ensimeServerProjectJars := resolveEnsimeJars("org.scala-lang", sbtScalaVersion, ensimeServerVersion.value)(ensimeResolvers.value))
```

I think just sbtScalaVersion is wrong since it's picking up the version from the project not the version from sbt.

**Comment by fommil** [comment]
you skipped the first part of my reply

**Comment by fommil** [comment]
I don't know how that would be wrong, sounds like a build configuration issue. Glad it's working.

**Comment by kbrowder** [comment]
Ya, it was basically a build configuration issue, that I misread, using scala 2.12...  The above worked for 2.11, and for 2.12 there's some wrangling with version numbers.

I'm not sure why I have to add the ensime*Jars but it doesn't seem to work without it.

I may think about adding that pull request for docs as you suggested.  It seems there's two cases you'd want to be able to use a proxy/mirror, one's in corporate firewall environments and the other's in bandwidth limited offices.  Pointing to specific jars on disk should be a last resort in either of these cases I think?

Anyways I'm off to the races thanks :)

**Comment by fommil** [comment]
It's not about bandwidth. Some places, one jar in all you can get through the admin.

**Comment by kbrowder** [comment]
I see, so that's a different scenario than I was thinking (or am in) though I guess that's also common.

(edit: this must be a really tough scenario for people to deal with in general, dependency trees have gotten pretty deep since the advent/popularity of maven)
