### ISSUE TITLE
coursier downloader not updating regularly?

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#321]
I'm pretty sure coursier is no longer updating the jar cache.

**Comment by gaydenko** [comment]
I guess you are right. From time to time to get something new I delete ensime related directories form the cache. I was sure it is expected situation for development branch :)

**Comment by fommil** [comment]
@alexarchambault did anything change in this area or is there something we need to do to make snapshots expire in the cache? https://github.com/ensime/ensime-sbt/blob/2.0/src/main/scala/CoursierHelper.scala#L75

**Comment by alexarchambault** [comment]
Ok, found it, I think. The line you're pointing at should look like [this one](https://github.com/alexarchambault/ammonium/blob/a506a30798188056b2b810d97de4cdf17923e8e6/amm/runtime/src/main/scala/ammonite/runtime/tools/DependencyThing.scala#L76-L82) (using all the "cache policies" in particular).

Sorry about it, I've been beaten by that too... :-\ I hope to come up with a smoother higher level API for coursier once 1.0 final is out.

The policies basically say "check the artifacts using TTL if it is changing", "download only if not in cache", etc. By default, it's just "download if not in cache" (I guess I could change that in the API too).

**Comment by fommil** [comment]
nice, well found!
