### ISSUE TITLE
coursier still not updating snapshots

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#331]
@alexarchambault

:point_up: [May 4, 2017 9:52 PM](https://gitter.im/coursier/coursier?at=590b947812f05b512a2d191f)

looks like sbt-ensime is still not updating the snapshot jars as expected... e.g.

```
ll ~/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/snapshots/org/ensime/core_2.12/2.0.0-SNAPSHOT/
total 1.3M
-rw-r--r-- 1 fommil fommil 1.3M Apr 21 15:01 core_2.12-2.0.0-SNAPSHOT.jar
-rw-r--r-- 1 fommil fommil   40 Apr 21 15:01 core_2.12-2.0.0-SNAPSHOT.jar.sha1
-rw-r--r-- 1 fommil fommil  47K May  1 17:19 core_2.12-2.0.0-SNAPSHOT.pom
-rw-r--r-- 1 fommil fommil   40 May  1 17:19 core_2.12-2.0.0-SNAPSHOT.pom.sha1
```

and on https://oss.sonatype.org/content/repositories/snapshots/org/ensime/api_2.12/2.0.0-SNAPSHOT/

``` 
api_2.12-2.0.0-SNAPSHOT.jar.md5    Mon May 01 16:19:30 UTC 2017    32    
api_2.12-2.0.0-SNAPSHOT.jar.sha1    Mon May 01 16:19:29 UTC 2017    40    
api_2.12-2.0.0-SNAPSHOT.pom    Mon May 01 16:19:28 UTC 2017    12505    
api_2.12-2.0.0-SNAPSHOT.pom.md5    Mon May 01 16:19:29 UTC 2017    32    
api_2.12-2.0.0-SNAPSHOT.pom.sha1    Mon May 01 16:19:29 UTC 2017    40
```

did we miss something out in https://github.com/ensime/ensime-sbt/blob/2.0/src/main/scala/CoursierHelper.scala#L80
maybe forgot something here? https://github.com/ensime/ensime-sbt/blob/2.0/src/main/scala/CoursierHelper.scala#L88

**Comment by fommil** [comment]
@timcharper

**Comment by alexarchambault** [comment]
The second line should take into account cache policies too, like done [here](https://github.com/alexarchambault/ammonium/blob/cb6efe091ea1b8fd83a65737cbb18fa4ba4d8eb1/amm/runtime/src/main/scala/ammonite/runtime/tools/DependencyThing.scala#L104-L111).

**Comment by fommil** [comment]
Thanks Alex!
