### ISSUE TITLE
Fix scalac-options/compiler-options

### ISSUE THREAD

**Issue by hedefalk** [ensime/ensime-sbt#339]
Sam, really sorry with all these questions, but what key am I to put the settings under:
With a ensime.sbt in project:

```
ensimeScalacOptions in ThisBuild:= Seq(
    "-feature",
    "-deprecation",
    "-Xlint",
    "-Ywarn-dead-code",
    "-Ywarn-numeric-widen",
    "-Xfuture",
    "-Ymacro-expand:discard"
)
```

I still get the default:

```
 :compiler-args ("-deprecation" "-unchecked" "-feature" "-language:postfixOps" "-language:implicitConversions" "-Xmax-classfile-name" "200" "-Xlint" "-Ywarn-dead-code" "-Ywarn-numeric-widen" "-Xfuture" "-Ywarn-unused-import" "-Ymacro-expand:discard")
```

And for all subprojects:
     
```
:scalac-options ("-deprecation" "-unchecked" "-feature" "-language:postfixOps" "-language:implicitConversions" "-Xmax-classfile-name" "200" "-feature" "-deprecation" "-Xlint" "-Ywarn-dead-code" "-Ywarn-numeric-widen" "-Xfuture" "-Ywarn-unused-import" "-Ymacro-expand:discard")
```

Removing in ThisBuild I get compiler-args fixed, but not scalac-options under the subprojects… I'm confused…

Sam Halliday @fommil 16:22

> scalac-options is ignored right now
> but will be used pretty soon
> (it's what Vishesh is working on)
> I think I'd have the same expectation as you in sbt-ensime so I think that's a bug
> can you raise one please?
> just copy / paste this discussion is fine
> 

Viktor Hedefalk @hedefalk 16:24
Sure!

Sam Halliday @fommil 16:24
oh, hold on, it's worse than I thought... you're still unable to change the :compiler-args
hmm, ok that should definitely be supported

**Comment by yyadavalli** [comment]
@hedefalk can you please try setting `scalacOptions`

https://github.com/ensime/ensime-sbt/blob/2.0/src/main/scala/EnsimePlugin.scala#L202

`ensimeScalacOptions` is a task that aggregates multiple sets of options, it is not a settingKey, may be we should add one or modify this, but I think that's a slightly different discussion.

I also think we want to maintain the same set of `scalacOptions` that are used by sbt for compilation
