### ISSUE TITLE
Deploy sbt-ensime to Bintray?

### ISSUE THREAD

**Issue by mindloaf** [ensime/ensime-sbt#342]
For users that use Artifactory to cache repo1, the sbt-ensime fails to cache properly (and is thus not usable) due to:

https://www.jfrog.com/jira/browse/RTFACT-6235

Please consider adding your plugin to [Bintray](http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html)

**Comment by fommil** [comment]
nope, maven central for the win.

**Comment by mindloaf** [comment]
Thanks for considering

**Comment by fommil** [comment]
you can publish locally as a workaround.

**Comment by mindloaf** [comment]
Heh, or Jfrog can, you know, actually fix the bug :-)

**Comment by fommil** [comment]
you'd think they'd care about paying users
