### ISSUE TITLE
test projects should depend on their compile phase

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#343]
damn, causes https://github.com/ensime/ensime-server/issues/1805

**Comment by fommil** [comment]
@yyadavalli I somehow missed this, even in our simple tests it's like this

```
 :id (:project "simple-build-sbt" :config "test")
 :depends nil
```

**Comment by yyadavalli** [comment]
@fommil I will take a look

**Comment by fommil** [comment]
that'd be awesome, thanks! I am a bit busy in the next few days.
