### ISSUE TITLE
still depending on scalaz

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#346]
the shading was supposed to have fixed this, but it didn't.  // reported by @puffnfresh on twitter

**Comment by fommil** [comment]
here's the evidence https://repo1.maven.org/maven2/org/ensime/sbt-ensime_2.10_0.13/1.12.13/sbt-ensime-1.12.13.pom

as a workaround, I think you can do this

```scala
addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.13" exclude("org.scalaz", "scalaz-concurrent_2.10"))
```

@alexarchambault may know more... is this a bug in coursier-shading or did I do it wrong?

**Comment by puffnfresh** [comment]
Thanks @fommil, I couldn't figure out the syntax.

I just `ensimeCompileOnly`  a go I get a lot of errors, then it spends a lot of time going through files and printing "Could not access type X in package Y, because it (or its dependencies) are missing" for each one. That seems like a separate issue that I should file, but the exclusion seems to be working.

:+1:

**Comment by fommil** [comment]
I think that's probably working as intended... you need to compile your project just once before using it. It's just calling `scalac` with all the correct flags that you'd expect, it's an advanced user convenience.

I had a project where an incremental recompile would take 10 minutes and I didn't really care what I broke downstream I just wanted to see the compile failures in my file (1 second compile). But it's also pretty useful for printing out after typer, etc. Basically I don't use `scalac` CLI anymore.

If you're in emacs you can `C-c C-b C` to compile the current file with this so you don't need to faff around getting the current filename.

**Comment by puffnfresh** [comment]
I've compiled the whole project before with sbt, do I have to also compile it outside of sbt?

**Comment by fommil** [comment]
nope, that should work. If you have a public project that reproduces the errors, then that might be a bug.

**Comment by fommil** [comment]
oh, don't forget your project path if it's a multi-project build! `foo/ensimeCompileOnly /path/to/foo.scala`

**Comment by fommil** [comment]
more here http://ensime.org/build_tools/sbt/#extra-tasks-and-commands

**Comment by alexarchambault** [comment]
@fommil When I publish locally ensime-sbt (I tested with sbt-coursier 1.0.0-RC8), I can't find scalaz in the dependencies of the plugin.

**Comment by fommil** [comment]
interesting, maybe I should just upgrade to RC8?

**Comment by fommil** [comment]
are you looking in the `.pom` **and** the `.ivy`?

**Comment by alexarchambault** [comment]
Yeah, both.

**Comment by fommil** [comment]
ok, I'll try too with your latest. Thanks for looking into it!

**Comment by fommil** [comment]
argh

```
[error] (shading:toShadeJars) java.lang.UnsupportedClassVersionError: coursier/shaded/com/tonicsystems/jarjar/transform/jar/JarProcessor : Unsupported major.minor version 52.0
```

**Comment by fommil** [comment]
maybe it's time for our sbt plugin to build on java 8...

**Comment by fommil** [comment]
but, I also don't see scalaz in the current `2.0` branch on `publishLocal`... is it possible this is a bug only in `publishSigned` usage?

**Comment by fommil** [comment]
I'm not able to reproduce with `publishLocalSigned`. What a mystery

**Comment by fommil** [comment]
I think I may have accidentally fixed this since the last release.

**Comment by alexarchambault** [comment]
Cool, then 😅
