### ISSUE TITLE
SLF4J Dependency not mentioned in the ensime.org instructions

### ISSUE THREAD

**Issue by ixxie** [ensime/ensime-sbt#347]
It seems a SLF4J dependency is not mentioned in the documentation; I had the following error:

    [error] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    [error] SLF4J: Defaulting to no-operation (NOP) logger implementation
    [error] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

which was resolved by adding `libraryDependencies += "org.slf4j" % "slf4j-simple" % "1.6.4"` to my `plugins.sbt`.

### Steps to reproduce

1. Install the ensime-sbt plugin as explained on http://ensime.org/build_tools/sbt/
2. run, for example, sbt ensimeConfig

**Comment by fommil** [comment]
we don't use slf4j, so it is likely that we are calling some task in your project that has this dependency.
