### ISSUE TITLE
The sbt plugin assumes that scala versions are publicly available

### ISSUE THREAD

**Issue by jvican** [ensime/ensime-sbt#350]
### Steps to reproduce

1. Use a scala version that you use locally and it's not published (a fork).
2. Run `ensimeConfig`.

### Expected behaviour
It generates an ensime config file.

### Actual behaviour
It fails with:
```
[error] ({.}/*:ensimeScalaJars) failed to resolve ((org.scala-lang:scalap,2.12.4-bin-SNAPSHOT),List(not found: https://repo1.maven.org/maven2/org/scala-lang/scalap/2.12.4-bin-SNAPSHOT/scalap-2.12.4-bin-SNAPSHOT.pom, not found: https://oss.sonatype.org/content/repositories/snapshots/org/scala-lang/scalap/2.12.4-bin-SNAPSHOT/scalap-2.12.4-bin-SNAPSHOT.pom))
[error] Missing task key: ensimeScalaJars
```

### Workaround
**None**. Note that it's not possible to modify `ensimeRepositoryUrls` to include the ivy cache because `CoursierHelper` assumes that the urls are maven repositories.
  
### Offending code
https://github.com/ensime/ensime-sbt/blob/2.0/src/main/scala/EnsimeCoursierPlugin.scala#L42-L48
  
It could be easily fixed by adding the ivy cache to the pack, though there's a comment advising against it.
  
**Question**: is there any reason why we're not reusing `resolvers`?
**Question**: what would the ideal solution be like?

**Comment by fommil** [comment]
- corructed local ivy caches directories are probably the single most common cause of server start errors. We definitely don't want it there by default.
- we could make the ensimeResolvers a public key (if it's not already) or make it handle more types of repos?

**Comment by fommil** [comment]
btw, another workaround is to just force the ensimeServerVersion to 2.12.3 for this project with `ensime.sbt` (that's what I'd do...)

**Comment by jvican** [comment]
1. The corruption error would only affect ``"The maven repositories to download the scala compiler, ensime-server and ensime-plugins jars", right?
2. It's not public, making `ensimeResolvers` public would probably be the best, yeah.
  
WRT your workaround, if I do that, I won't be able to get go to definition for things I add in my local fork, right? So I'll need to do that + replacing manually instances of `2.12.3` by `$MY_SCALA_VERSION` in the `.ensime` file.

**Comment by fommil** [comment]
Yeah making it public could be good. It might even make sense to not have the sonatype snapshots in the defaults, and instead make that opt-in, for extra faster startups on "stable" releases.

Your project should be fine. Remember this is the version of scala that the server is running on, it's got nothing to do with the project it is running against.

That said... if you're working on adding timeout info messages, I think I'd like you to see how that plays with the PC so :+1: to 2.

**Comment by jvican** [comment]
> Your project should be fine. Remember this is the version of scala that the server is running on, it's got nothing to do with the project it is running against.
  
Aha, great! It wasn't clear to me.
  
> That said... if you're working on adding timeout info messages, I think I'd like you to see how that plays with the PC so 👍 to 2.
  
I'm adding fixing this ticket to my todo list, will try to get back to it soon!

**Comment by fommil** [comment]
should be an easy one. I'd be happy with you removing snapshots from the default list in light of #349

**Comment by fommil** [comment]
is this solved with something like

```
ensimeRepositoryUrls += "https://oss.sonatype.org/content/repositories/snapshots/"
```

but with your repo in the list?

Whatever you put in here must be parsable by `coursier.MavenRepository`

**Comment by jvican** [comment]
I haven't tried, but the Scala version is from a local fork, and `publishLocal`ed, so if you can specify a local repository to `ensimeRepositoryUrls` should work.

**Comment by fommil** [comment]
yup, that's what it's for. You might need to do something to convert the ivy repo into a maven repo layout, or publish as maven too.
