### ISSUE TITLE
ensimeJavaFlags is repeating

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#352]
If I use `ensimeJavaFlags in ThisBuild` it gets repeated once per project. We should only reference this once, it's top level.

**Comment by yyadavalli** [comment]
Hi @fommil I am not sure how this is possible. I just checked the code and it is referenced only in the top level `EnsimeConfig`. Can you please post a gist with a `.ensime` with the issue.

**Comment by fommil** [comment]
I'll just send a PR with a fix when I'm next around here.

**Comment by fommil** [comment]
*narrator: he didn't*
