### ISSUE TITLE
Skip over scalajs and scala-native project variants

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#359]
They both use a massive hack that mutates the name of your project the somethingJvm and adds new ones. We should probably ignore the non-JVM variants.

**Comment by fommil** [comment]
Workaround for now is to restrict ensimeConfig to the subset of jvm projects manually.

**Comment by joroKr21** [comment]
It runs update on all projects regardless of the passed list and fails if there are unresolved dependencies (in the case of shapeless unresolved Scala native libs). Instead it should probably run update only on the restricted subset.

**Comment by fommil** [comment]
it does work for restricted projects. The problem is that scalajs and scala-native are massive hacks, so we probably need further hacks.

**Comment by fommil** [comment]
@jvican that hack I was talking about ^^^
