### ISSUE TITLE
get all tasks working under sbt 1.0

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#365]
@vovapolu do you have an upstream ticket for this?

**Comment by fommil** [comment]
could be https://github.com/sbt/sbt/issues/3572

**Comment by fommil** [comment]
https://github.com/jeffreyolchovy/sbt-check possible inspiration for `ensimeCompileOnly`

**Comment by yyadavalli** [comment]
@fommil I don't think it's a lot of help for `ensimeCompileOnly`. It's just adding the scalac option `-Ystop-after:typer` in that task.

https://github.com/jeffreyolchovy/sbt-check/blob/master/src/main/scala/sbtcheck/AbstractCheckPlugin.scala#L22

I think we need to look at the zinc API, to compile a file.

**Comment by vovapolu** [comment]
@yyadavalli `testOnly` is unfinished! So I doubt that issue is resolved.

**Comment by yyadavalli** [comment]
Sorry I forgot about that
