### ISSUE TITLE
Missing dependencies added to depenencyClasspath

### ISSUE THREAD

**Issue by korommatyi** [ensime/ensime-sbt#370]
Hi,

I need to manually add some jars to the classpath in the `build.sbt` like:

```scala
dependencyClasspath in Compile ++= sparkJars(sparkVersion.value)
dependencyClasspath in Test ++= sparkJars(sparkVersion.value)
```
These dependencies are missing in the `.ensime` file generated by the ensime plugin. (I guess, I should be able to find them under the `:compile-deps` key.)

### Steps to reproduce

1. Add a jar to the `dependencyClasspath` manually in the `build.sbt` file.
2. Generate `.ensime` file by the sbt plugin.

### Expected behaviour

1. Jars show up in the `.ensime` file.
2. Editor doesn't complain when importing from these jars.

### Actual behaviour

No jars and false errors reported by the editor.

On the short term, I would be happy to learn how to add the jars manually in the `ensime.sbt` file if it is possible (this would lead to code duplication, I know...). On the long term, I'm willing to give it a try to fix this and send a pull request.

Also, if you need an example mini project on github, let me know.

Thanks and cheers!

**Comment by yyadavalli** [comment]
@korommatyi Can you please create a minimal reproduction for this? 
I am not sure what `sparkJars(...)` is adding, so I cant reproduce this.

**Comment by korommatyi** [comment]
@yyadavalli Sure, here it is: https://github.com/korommatyi/ensime-sbt-bug
Thanks for checking this out!

**Comment by yyadavalli** [comment]
Part of the problem is adding the dependencies manually

It is better to use the unmanaged dependencies
http://www.scala-sbt.org/0.13/docs/Library-Dependencies.html

We pick up the dependencies listed in `managedClasspath` and `unmanagedClasspath`. 

`dependencyClasspath` is an aggregate that's calculated using the above and a few more things.

**Comment by korommatyi** [comment]
Thanks @yyadavalli, adding the extra jars to `unmanagedJars` instead of `dependencyClasspath` indeed solves the problem!

Out of curiosity, isn't it safer to just pick up `dependencyClasspath` as it is? Duplicating the calculation seems error prone to me (what if `sbt` changes something, then you need to duplicate the change here as well). Is there any special reason not to just blindly copy `dependencyClasspath`?

**Comment by korommatyi** [comment]
Oh, I've learned why we add the jars to `dependencyClasspath`. We don't want them to be included in the build result but pick them up at runtime. Adding the jars to `unmanagedJars` copies them to `stage/lib`.

**Comment by yyadavalli** [comment]
I think `depenencyClasspath` includes entries from `target` folders, that's the reason we use the individual components. I'll think about what we can do to resolved this.

**Comment by yyadavalli** [comment]
@fommil Your thoughts on this, do you think we can use dependencyClasspath directly with some filtering, of course.

**Comment by fommil** [comment]
this sounds like it is working as intended. ENSIME is for compiletime not runtime classes. It sounds like the build in question is hacking around ivy, which already has the concept of compile / provided / runtime deps. If such hacks are to be used, a second round of hacks is needed for things that don't expect hacks.

**Comment by yyadavalli** [comment]
Yeah, it's hacky, the jars are manually put in place both at compile time and runtime. But sbt already works around that by providing a `dependencyClasspath` task. So if we use the same I think we should be okay. Also the filter I mentioned is to remove the project class files that get included in `dependencyClasspath`.

**Comment by fommil** [comment]
calling `dependencyClasspath` will call compile on all dependent projects. Even if you filter them out afterwards.

**Comment by yyadavalli** [comment]
Oh, `dependencyClasspath` is a build level task. That would mess up the project info a lot.
I agree what we have is prefect.
