### ISSUE TITLE
Project with integration tests does not respect test multi-project dependencies

### ISSUE THREAD

**Issue by ANorwell** [ensime/ensime-sbt#372]
This is as of ensime-sbt 2.0.1.

I have made a repro repo of this issue: https://github.com/ANorwell/ensime_bug.

This has a multi-project build. One of the projects declares a dependency on the tests of the first project. Additionally, the project includes integration test configuration. The resulting generated ensime file doesn't properly include the test dependency. Removing the integration test config makes this go away.

Example from the .ensime file (included in the repo):

```
    :id (:project "b" :config "test")
    :depends ((:project "a" :config "compile") (:project "b" :config "compile"))
```

**Comment by yyadavalli** [comment]
@ANorwell Just to clarify, even when you remove the integration test config, the `:depends` are still the same as above right?

**Comment by ANorwell** [comment]
@yyadavalli Yes, that seems to be true. The diff to .ensime when I remove integration tests are below. It's also here on the reproduction repo: https://github.com/ANorwell/ensime_bug/compare/no_int

I'm not sure how that matches what I wrote when I wrote the issue, when I thought I was seeing the integration test config as required. That doesn't seem to be true.

```
diff --git a/.ensime b/.ensime
index 60b3092..a868d19 100644
--- a/.ensime
+++ b/.ensime
@@ -26,7 +26,7 @@
    :name "b"
    :source-roots ("/Users/anorwell/work/ensime_bug/b/src/test/scala")
    :targets ("/Users/anorwell/work/ensime_bug/b/target/scala-2.10/classes")
-   :test-targets ("/Users/anorwell/work/ensime_bug/b/target/scala-2.10/classes" "/Users/anorwell/work/ensime_bug/b/target/scala-2.10/test-classes")
+   :test-targets ("/Users/anorwell/work/ensime_bug/b/target/scala-2.10/test-classes")
    :depends-on-modules ("a")
    :compile-deps nil
    :runtime-deps nil
@@ -71,15 +71,6 @@
     :library-jars nil
     :library-sources nil
     :library-docs ("/Users/anorwell/work/ensime_bug/b/target/scala-2.10/b_2.10-0.1-SNAPSHOT-javadoc.jar")) (
-    :id (:project "b" :config "it")
-    :depends ((:project "a" :config "compile") (:project "b" :config "compile"))
-    :sources nil
-    :targets ("/Users/anorwell/work/ensime_bug/b/target/scala-2.10/classes")
-    :scalac-options ("-feature" "-deprecation" "-Xlint" "-Ywarn-dead-code" "-Ywarn-numeric-widen" "-Xfuture" "-Ymacro-no-expand")
-    :javac-options nil
-    :library-jars nil
-    :library-sources nil
-    :library-docs nil) (
     :id (:project "b" :config "test")
     :depends ((:project "a" :config "compile") (:project "b" :config "compile"))
     :sources ("/Users/anorwell/work/ensime_bug/b/src/test/scala")
diff --git a/.gitignore b/.gitignore
```

**Comment by yyadavalli** [comment]
The main issue was we were not handling multiple configurations like `test->test;compile->compile`. a workaround might be something like this
```
lazy val server = project.in(file("server")).dependsOn(
  core,
  core % "test->test",
  core % "it->it"
)
```

**Comment by fommil** [comment]
@ANorwell converting that example project into a PR that fails would be really awesome, and make it a lot easier for somebody to fix it. Have a look under `src/sbt-tests` for examples.

**Comment by fommil** [comment]
oh, nevermind, I didn't see the PR already :smile:

**Comment by fommil** [comment]
I think we're still missing the case where the dep looks like `commontest % "test,it"`

**Comment by yyadavalli** [comment]
Yes, it was not in the docs, I missed it. Will fix it soon.

**Comment by fommil** [comment]
At least there is a simple workaround :smile:

**Comment by yyadavalli** [comment]
Yes, just add the arrows

**Comment by timcharper** [comment]
Thanks for this, I just hit this, discovered the same workaround, and was about to report it, only to discover that the fix was made and just barely released (thank you, too, @fommil, for this!)

**Comment by timcharper** [comment]
Hmm, I thought this would resolve my issue; I've upgraded to ensime-sbt-2.5.1 and the test dependencies weren't generated correctly. I had to modify them by hand, manually.
