### ISSUE TITLE
usage of ensimeRepositoryUrls key at global.sbt for snapshots repo doesn't work

### ISSUE THREAD

**Issue by strobe** [ensime/ensime-sbt#384]
this issue result of https://github.com/ensime/ensime-sbt/pull/382

### Steps to reproduce

1. put following code to ~/.sbt/0.13/global.sbt
```scala
import org.ensime.EnsimeCoursierKeys._
import org.ensime.EnsimeKeys._

ensimeRepositoryUrls += "https://oss.sonatype.org/content/repositories/snapshots/"
ensimeServerVersion in ThisBuild := "3.0.0-SNAPSHOT"
ensimeProjectServerVersion in ThisBuild := "3.0.0-SNAPSHOT"
```
2. try to run `sbt ensimeConfig` at some project  

### Expected behaviour

generated ensimeConfig with dev version of ensimeServerJars

### Actual behaviour

```
[error] ({.}/*:ensimeServerJars) failed to resolve ((org.ensime:server_2.12,3.0.0-SNAPSHOT),List(not found: https://repo1.maven.org/maven2/org/ensime/server_2.12/3.0.0-SNAPSHOT/server_2.12-3.0.0-SNAPSHOT.pom))
```

### For other details see  https://github.com/ensime/ensime-sbt/pull/382

**Comment by fommil** [comment]
probably the docs are missing an `in ThisBuild`

**Comment by strobe** [comment]
you are right,
 fix here https://github.com/ensime/ensime.github.io/pull/257
