### ISSUE TITLE
sbt ensime windows 10

### ISSUE THREAD

**Issue by khannaum** [ensime/ensime-sbt#389]
To do so, add it to ~/.sbt/1.0/plugins/plugins.sbt (create if necessary) as such:

addSbtPlugin("org.ensime" % "sbt-ensime" % "2.1.0")

**kindly tell where is ~ on windows 10**

...

**Comment by amanjpro** [comment]
http://lmgtfy.com/?q=%22~%22+equivalent+on+windows
