### ISSUE TITLE
You have a different version of scala for ENSIME and my project

### ISSUE THREAD

**Issue by crazyrunsnail** [ensime/ensime-sbt#390]
I'm  newer to scala and sbt.
I install sbt by brew on my mac, and generate a project by sbt using `sbt new sbt/scala-seed.g8`.
After that I add ENSIME by adding `addSbtPlugin("org.ensime" % "sbt-ensime" % "2.1.0")` in the file `~/.sbt/1.0/plugins/plugins.sbt`.
Then I enter the project directory, type `sbt`  and  `ensimeConfig` , get the error on the below:
```
[warn] You have a different version of scala for ENSIME (2.12.4) and spark-demo (2.11.12).
[warn] If this is not what you intended, try fixing your build with:
[warn]   scalaVersion in ThisBuild := "2.11.12"
[warn] in your build.sbt, or override the ENSIME scala version with:
[warn]   ensimeScalaVersion in ThisBuild := "2.11.12"
[warn] in a ensime.sbt: http://ensime.org/build_tools/sbt/#customise
[error] org.ensime.EnsimePlugin$$anon$1: To ignore this error (i.e. you have multiple scala versions), add `ensimeIgnoreScalaMismatch in ThisBuild := true` or `ensimeIgnoreScalaMismatch in LocalProject("spark-demo") := true` to your ensime.sbt
[error] (*:ensimeConfig) org.ensime.EnsimePlugin$$anon$1: To ignore this error (i.e. you have multiple scala versions), add `ensimeIgnoreScalaMismatch in ThisBuild := true` or `ensimeIgnoreScalaMismatch in LocalProject("spark-demo") := true` to your ensime.sbt
[error] Total time: 37 s, completed Feb 9, 2018 8:56:20 AM
```
According the warning , I add `ensimeScalaVersion := "2.11.12"` to the build.sbt.  But It dosen't work.
May I add a file name `ensime.sbt` by myself?  I'm confused...

**Comment by avdv** [comment]
> May I add a file name ensime.sbt by myself? I'm confused...

Yes. See http://ensime.org/build_tools/sbt/#customise

You forgot the `in ThisBuild` part.

**Comment by crazyrunsnail** [comment]
@avdv I add `ensimeScalaVersion in ThisBuild := "2.11.12"` to `build.sbt`, but it also prints the warn and error.
I wonder how to control the version of scala in the ensime?
In my understanding, run `ensimeConfig` will auto generate the file named `ensime.sbt` just like `eslint` does, why should I add it manually?

**Comment by avdv** [comment]
@crazyrunsnail sorry, missed your reply...

`ensimeConfig` does not generate an `*.sbt` file, it generates the `.ensime` config file.

Did you check https://ensime.github.io/build_tools/sbt/#common-mistakes ?

Could you create a git repository which reproduces the problem?

**Comment by crazyrunsnail** [comment]
@avdv thanks for your reply...I think I can resolve it. agains, thanks you very much!

**Comment by ahakanbaba** [comment]
@avdv  A question from a scala newby. Thank you for your help in advance. 
What is the problem of having different scala versions between the Ensime and the application-under-development ? 

Should we expect some errors if the two versions are different? Why should we care ? 

The scala version of the application-under-development comes from its `build.sbt` file like `scalaVersion := "2.11.12" `. Where does the version of the Ensime come ? Is that the scala version used to compile ensime-server ?

**Comment by hsienchiaolee** [comment]
@crazyrunsnail Did you ever resolve this? If so, how did you resolve it? I am having the same issue as you describe here.

• Ensured my plugin is imported from `~/.sbt/1.0/plugins/plugins.sbt`
• Ensured `ensimeScalaVersion in ThisBuild := "2.12.6"` inside my `ensime.sbt`
