### ISSUE TITLE
[FEATURE REQUEST] Any plans on Mill support?

### ISSUE THREAD

**Issue by NightMachinery** [ensime/ensime-sbt#395]
I believe [Mill](https://github.com/lihaoyi/mill/) is quite superior to SBT, especially for the kind of projects ENSIME is most good for: small codebases, rapid prototypes, scratchpads ... .
It would be excellent if ensime-mill would get created.

**Comment by fommil** [comment]
the best place to ask would be the mill gitter room. This is an sbt plugin.
