### ISSUE TITLE
Can't find source code for sbt-sensible

### ISSUE THREAD

**Issue by justinhj** [ensime/ensime-sbt#402]
In the project/plugins.sbt I see this dependency. I've been trying to track down the source code for it but it seems to be deleted from github and private on gitlab. Is there a publicly available copy of the source?

addSbtPlugin("com.fommil" % "sbt-sensible" % "2.4.2")

**Comment by SethTisue** [comment]
there are several forks on GitLab, not sure which one is most up-to-date:

* https://gitlab.com/leonard.ehrenfried/sbt-sensible
* https://gitlab.com/avdv/sbt-sensible
* https://gitlab.com/justinhj/sbt-sensible

(I needed the source code as well in order to troubleshoot a problem in the Scala community build)

**Comment by justinhj** [comment]
Thanks Seth, I also saw those and that last one is my fork of a fork, but yeah was also curious which is the canonical version

**Comment by SethTisue** [comment]
LOL, I didn’t notice the name matched :-)

**Comment by fommil** [comment]
Come on guys, this is literally the point of artefactories like Maven Central. Why are you looking in git repos when updateSbtClassifiers will do this for you.

My profile page on github already tells you where to look. I'm not even vaguely interested in reviving it.

**Comment by justinhj** [comment]
Thanks for the heads up. I wouldn't have thought of reading your github profile to find where the old gitlab repos are but there it is.

**Comment by fommil** [comment]
updateSbtClassifiers downloads the source of your plugins. I still don't understand why you're looking for git repos.

**Comment by justinhj** [comment]
That's good to know! Will use that if I have this need in the future.
