### ISSUE TITLE
Not a valid key: gen-ensime

### ISSUE THREAD

**Issue by rafael** [ensime/ensime-sbt#73]
Hi all,

I've been using ensime for a while it has been working nicely. However, today I was having an issue with an specific project and tried to install the ensime-sbt plugin from my local with sbt plublishLocal and now it doesn't seem to find it, I always get this error:

```
> gen-ensime
[error] Not a valid command: gen-ensime
[error] Not a valid project ID: gen-ensime
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: gen-ensime
[error] gen-ensime
```

and my plugins.sbt has the following:

```
addSbtPlugin("org.ensime" % "ensime-sbt" % "0.1.5-SNAPSHOT")
```

```
$ sbt --version
sbt launcher version 0.13.6
```

Any idea why this might be happening ? 

Thanks!

**Comment by drozzy** [comment]
I am getting this problem currently. Running Win10, sbt version 0.13.8 and my ~/.sbt/plugins/plugins.sbt looks like:

    resolvers += Resolver.sonatypeRepo("snapshots")

    addSbtPlugin("org.ensime" % "ensime-sbt" % "0.2.0")

**Comment by rorygraves** [comment]
@drozzy Can you confirm what you type and what you see as well as your sbt version please?

**Comment by edani** [comment]
@drozzy   For sbt 0.13, the filename should be `~/.sbt/0.13/plugins/plugins.sbt`

**Comment by bonchef** [comment]
I could not seem to find any help for a similar issue in Cygwin.  Took me a while to figure that out and would like to share:

If you install SBT on Windows, despite you can run SBT from Cygwin, the .sbt still resides under Windows (default seems to be %user%).  I tried long to trouble shoot my SBT plugin config under my Cygwin home dir which obviously had no effect.
