### ISSUE TITLE
append default compiler warnings

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-sbt#93]
It would be good if we automatically added a bunch of default `:compiler-args` warnings to the presentation compiler, even if the main build doesn't have them, as per https://github.com/ensime/ensime-server/issues/1080

e.g.

```
      "-feature",
      "-deprecation",
      "-Xlint",
      "-Yinline-warnings",
      "-Yno-adapted-args",
      "-Ywarn-dead-code",
      "-Ywarn-numeric-widen",
      "-Ywarn-value-discard",
      "-Xfuture"
```

and for scala 2.11 also

```
      "-Ywarn-unused-import"
```

This means a lot more orange squigglies for people and better code quality all around.

**Comment by aemoncannon** [comment]
Last time I checked the pres compiler wouldn't support a lot of extended
options, YMMV

**Comment by fommil** [comment]
@aemoncannon it seems to work quite well these days! Probably breaks for 2.9 but I'm seeing at least some of them work in 2.10 and 2.11.
